import { MigrationInterface, QueryRunner } from "typeorm";

export class SyncSchema1784615760037 implements MigrationInterface {
    name = 'SyncSchema1784615760037'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "material" DROP CONSTRAINT "FK_fb825ba8148529711b3d0052cd6"`);
        await queryRunner.query(`ALTER TABLE "comments" DROP CONSTRAINT "FK_0d47ff3107d25a3e622d1aa9cea"`);
        await queryRunner.query(`ALTER TABLE "answer_task" DROP CONSTRAINT "FK_4177e5c68c0f47895d0ade363b3"`);
        await queryRunner.query(`ALTER TABLE "answer_task" DROP CONSTRAINT "FK_d1bb0fa3821cf4a823e1be6420a"`);
        await queryRunner.query(`ALTER TABLE "assignments" DROP CONSTRAINT "FK_dfe0b834578448cce571c120847"`);
        await queryRunner.query(`ALTER TABLE "portofolios" DROP CONSTRAINT "FK_9d041c43c782a9135df1388ae16"`);
        await queryRunner.query(`ALTER TABLE "portofolios" DROP CONSTRAINT "FK_154136295c649bd370330be4501"`);
        await queryRunner.query(`ALTER TABLE "faqs" DROP CONSTRAINT "FK_10c7e15fda651a1ed577cd6f88c"`);
        await queryRunner.query(`ALTER TABLE "benefit_category" DROP CONSTRAINT "FK_e53cf775c4c30985898e10b3132"`);
        await queryRunner.query(`ALTER TABLE "flow_category" DROP CONSTRAINT "FK_e13e00da644bc6ce5180a0fb90f"`);
        await queryRunner.query(`ALTER TABLE "superiority" DROP CONSTRAINT "FK_c34720564c7fa06cea20d4dff75"`);
        await queryRunner.query(`ALTER TABLE "gallery" DROP CONSTRAINT "FK_538f84f5155921ca47a7ee474cb"`);
        await queryRunner.query(`ALTER TABLE "installment" DROP CONSTRAINT "FK_9bc2223d71ca2cd6beb891f816c"`);
        await queryRunner.query(`ALTER TABLE "payments" DROP CONSTRAINT "FK_398ad2aad8f28ebd953cf63ba47"`);
        await queryRunner.query(`ALTER TABLE "payments" DROP CONSTRAINT "FK_ffffb1021d14348ae16f0cf7051"`);
        await queryRunner.query(`ALTER TABLE "payments" DROP CONSTRAINT "FK_ba748cc92803680791eaab0f31d"`);
        await queryRunner.query(`ALTER TABLE "certificates" DROP CONSTRAINT "FK_4a6ffdc5c6616ca525f60898f5f"`);
        await queryRunner.query(`ALTER TABLE "certificates" DROP CONSTRAINT "FK_87bc2a5d85fed3f1a2e07d86942"`);
        await queryRunner.query(`ALTER TABLE "user_courses" DROP CONSTRAINT "FK_d23d4f7772d181abfb4ff25ac76"`);
        await queryRunner.query(`ALTER TABLE "user_courses" DROP CONSTRAINT "FK_31705317a82c5c6057d36f6bca8"`);
        await queryRunner.query(`ALTER TABLE "course_questions" DROP CONSTRAINT "FK_2141a01e67ebab8aed7eb4b5f02"`);
        await queryRunner.query(`ALTER TABLE "mentors" DROP CONSTRAINT "FK_20cbfca83ecf51eadd3f4ff0032"`);
        await queryRunner.query(`ALTER TABLE "alumni" DROP CONSTRAINT "FK_3dcca2bc9a925f0206e18a7baa9"`);
        await queryRunner.query(`ALTER TABLE "course_flow" DROP CONSTRAINT "FK_da82c730e16c96240b90d0f2fca"`);
        await queryRunner.query(`ALTER TABLE "program_benefits" DROP CONSTRAINT "FK_a3a99572bc9e518f60697636eb7"`);
        await queryRunner.query(`ALTER TABLE "mentoring" DROP CONSTRAINT "FK_08301855b186e5e01c43d4f07af"`);
        await queryRunner.query(`ALTER TABLE "registrations" DROP CONSTRAINT "FK_41b2fb089361275d6e5b29118c3"`);
        await queryRunner.query(`ALTER TABLE "registrations" DROP CONSTRAINT "FK_422065c0547c29d258d2aafe069"`);
        await queryRunner.query(`ALTER TABLE "course" DROP CONSTRAINT "FK_3126d08fc69f21ced5b9a4e8223"`);
        await queryRunner.query(`ALTER TABLE "course" DROP CONSTRAINT "FK_cdce265cc9c2575fd5124dfdbfa"`);
        await queryRunner.query(`ALTER TABLE "user_answers" DROP CONSTRAINT "FK_932636e0ba18fc9dedac59aed20"`);
        await queryRunner.query(`ALTER TABLE "user_answers" DROP CONSTRAINT "FK_b50fdf127cd4e230c5acb71a905"`);
        await queryRunner.query(`ALTER TABLE "user_answers" DROP CONSTRAINT "FK_bf422127c8fab65abcdd772e26f"`);
        await queryRunner.query(`ALTER TABLE "answers" DROP CONSTRAINT "FK_3c08617c5f034c4971b4738a615"`);
        await queryRunner.query(`ALTER TABLE "questions" DROP CONSTRAINT "FK_a8d79717c0dea3a67b2f37a32a3"`);
        await queryRunner.query(`ALTER TABLE "scores" DROP CONSTRAINT "FK_83742310b1ddb2a60525f3e9a1f"`);
        await queryRunner.query(`ALTER TABLE "scores" DROP CONSTRAINT "FK_b49b6e9e9b553654f33b7fd2365"`);
        await queryRunner.query(`ALTER TABLE "quiz_progresses" DROP CONSTRAINT "FK_310eff946ea2abb350d260603e2"`);
        await queryRunner.query(`ALTER TABLE "quiz_progresses" DROP CONSTRAINT "FK_246a41b5cf841ad8138dfbd34e0"`);
        await queryRunner.query(`ALTER TABLE "quiz" DROP CONSTRAINT "FK_8c7de4e4d4401526b4c9fa96807"`);
        await queryRunner.query(`ALTER TABLE "weeks" DROP CONSTRAINT "FK_b69181682249c347c225f57b818"`);
        await queryRunner.query(`ALTER TABLE "session_progresses" DROP CONSTRAINT "FK_3fdcbab09e1e09dabb560c61b8c"`);
        await queryRunner.query(`ALTER TABLE "session_progresses" DROP CONSTRAINT "FK_d2ad48a6b17a0e2e49f0448c94b"`);
        await queryRunner.query(`ALTER TABLE "logbook" DROP CONSTRAINT "FK_d4bcf4cb786b2aa92cb725e334d"`);
        await queryRunner.query(`ALTER TABLE "mentor_logbook" DROP CONSTRAINT "FK_26e646717dbc68eb7c083cff0dc"`);
        await queryRunner.query(`ALTER TABLE "mentor_logbook" DROP CONSTRAINT "FK_eb81580d284633ce9e64002821d"`);
        await queryRunner.query(`ALTER TABLE "session" DROP CONSTRAINT "FK_77fcf90289c4a3fafca6a123100"`);
        await queryRunner.query(`ALTER TABLE "attendance" DROP CONSTRAINT "FK_de7d9a1aced2983b37c6d8ece55"`);
        await queryRunner.query(`ALTER TABLE "attendance" DROP CONSTRAINT "FK_557708c43c7ff517d34cd577482"`);
        await queryRunner.query(`ALTER TABLE "mentor_biodata" DROP CONSTRAINT "FK_c0c27aa65c8c2919f26b8dca818"`);
        await queryRunner.query(`ALTER TABLE "week_progresses" DROP CONSTRAINT "FK_6874c79eafd79eba86ef7e6f140"`);
        await queryRunner.query(`ALTER TABLE "week_progresses" DROP CONSTRAINT "FK_b45ebee048a3f25dea303a1e16e"`);
        await queryRunner.query(`ALTER TABLE "category_course_types_course_type" DROP CONSTRAINT "FK_e3152cae5550f3109be808b3d81"`);
        await queryRunner.query(`ALTER TABLE "category_course_types_course_type" DROP CONSTRAINT "FK_7b1a079b4b172de4b7d4c4c28cd"`);
        await queryRunner.query(`ALTER TABLE "mentor_technologies" DROP CONSTRAINT "FK_479f4942a07f02e2ccdea14e9bf"`);
        await queryRunner.query(`ALTER TABLE "mentor_technologies" DROP CONSTRAINT "FK_86903a2ddb934091b9f4b21fa4c"`);
        await queryRunner.query(`ALTER TABLE "kelas_technologies" DROP CONSTRAINT "FK_77113e55b2a2023499da5b40f6e"`);
        await queryRunner.query(`ALTER TABLE "kelas_technologies" DROP CONSTRAINT "FK_4f92d42fe71299ee0aa072ced36"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_e3152cae5550f3109be808b3d8"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_7b1a079b4b172de4b7d4c4c28c"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_479f4942a07f02e2ccdea14e9b"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_86903a2ddb934091b9f4b21fa4"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_77113e55b2a2023499da5b40f6"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_4f92d42fe71299ee0aa072ced3"`);
        await queryRunner.query(`ALTER TABLE "paragraph" RENAME COLUMN "paragraf" TO "paragraphs"`);
        await queryRunner.query(`CREATE SEQUENCE IF NOT EXISTS "material_id_seq" OWNED BY "material"."id"`);
        await queryRunner.query(`ALTER TABLE "material" ALTER COLUMN "id" SET DEFAULT nextval('"material_id_seq"')`);
        await queryRunner.query(`ALTER TABLE "material" ALTER COLUMN "id" DROP DEFAULT`);
        await queryRunner.query(`CREATE SEQUENCE IF NOT EXISTS "comments_id_seq" OWNED BY "comments"."id"`);
        await queryRunner.query(`ALTER TABLE "comments" ALTER COLUMN "id" SET DEFAULT nextval('"comments_id_seq"')`);
        await queryRunner.query(`ALTER TABLE "comments" ALTER COLUMN "id" DROP DEFAULT`);
        await queryRunner.query(`CREATE SEQUENCE IF NOT EXISTS "answer_task_id_seq" OWNED BY "answer_task"."id"`);
        await queryRunner.query(`ALTER TABLE "answer_task" ALTER COLUMN "id" SET DEFAULT nextval('"answer_task_id_seq"')`);
        await queryRunner.query(`ALTER TABLE "answer_task" ALTER COLUMN "id" DROP DEFAULT`);
        await queryRunner.query(`CREATE SEQUENCE IF NOT EXISTS "assignments_id_seq" OWNED BY "assignments"."id"`);
        await queryRunner.query(`ALTER TABLE "assignments" ALTER COLUMN "id" SET DEFAULT nextval('"assignments_id_seq"')`);
        await queryRunner.query(`ALTER TABLE "assignments" ALTER COLUMN "id" DROP DEFAULT`);
        await queryRunner.query(`CREATE SEQUENCE IF NOT EXISTS "portofolios_id_seq" OWNED BY "portofolios"."id"`);
        await queryRunner.query(`ALTER TABLE "portofolios" ALTER COLUMN "id" SET DEFAULT nextval('"portofolios_id_seq"')`);
        await queryRunner.query(`ALTER TABLE "portofolios" ALTER COLUMN "id" DROP DEFAULT`);
        await queryRunner.query(`CREATE SEQUENCE IF NOT EXISTS "course_type_id_seq" OWNED BY "course_type"."id"`);
        await queryRunner.query(`ALTER TABLE "course_type" ALTER COLUMN "id" SET DEFAULT nextval('"course_type_id_seq"')`);
        await queryRunner.query(`ALTER TABLE "course_type" ALTER COLUMN "id" DROP DEFAULT`);
        await queryRunner.query(`CREATE SEQUENCE IF NOT EXISTS "faqs_id_seq" OWNED BY "faqs"."id"`);
        await queryRunner.query(`ALTER TABLE "faqs" ALTER COLUMN "id" SET DEFAULT nextval('"faqs_id_seq"')`);
        await queryRunner.query(`ALTER TABLE "faqs" ALTER COLUMN "id" DROP DEFAULT`);
        await queryRunner.query(`CREATE SEQUENCE IF NOT EXISTS "category_id_seq" OWNED BY "category"."id"`);
        await queryRunner.query(`ALTER TABLE "category" ALTER COLUMN "id" SET DEFAULT nextval('"category_id_seq"')`);
        await queryRunner.query(`ALTER TABLE "category" ALTER COLUMN "id" DROP DEFAULT`);
        await queryRunner.query(`CREATE SEQUENCE IF NOT EXISTS "installment_id_seq" OWNED BY "installment"."id"`);
        await queryRunner.query(`ALTER TABLE "installment" ALTER COLUMN "id" SET DEFAULT nextval('"installment_id_seq"')`);
        await queryRunner.query(`ALTER TABLE "installment" ALTER COLUMN "id" DROP DEFAULT`);
        await queryRunner.query(`CREATE SEQUENCE IF NOT EXISTS "payments_id_seq" OWNED BY "payments"."id"`);
        await queryRunner.query(`ALTER TABLE "payments" ALTER COLUMN "id" SET DEFAULT nextval('"payments_id_seq"')`);
        await queryRunner.query(`ALTER TABLE "payments" ALTER COLUMN "id" DROP DEFAULT`);
        await queryRunner.query(`CREATE SEQUENCE IF NOT EXISTS "certificates_id_seq" OWNED BY "certificates"."id"`);
        await queryRunner.query(`ALTER TABLE "certificates" ALTER COLUMN "id" SET DEFAULT nextval('"certificates_id_seq"')`);
        await queryRunner.query(`ALTER TABLE "certificates" ALTER COLUMN "id" DROP DEFAULT`);
        await queryRunner.query(`CREATE SEQUENCE IF NOT EXISTS "user_courses_id_seq" OWNED BY "user_courses"."id"`);
        await queryRunner.query(`ALTER TABLE "user_courses" ALTER COLUMN "id" SET DEFAULT nextval('"user_courses_id_seq"')`);
        await queryRunner.query(`ALTER TABLE "user_courses" ALTER COLUMN "id" DROP DEFAULT`);
        await queryRunner.query(`CREATE SEQUENCE IF NOT EXISTS "course_questions_id_seq" OWNED BY "course_questions"."id"`);
        await queryRunner.query(`ALTER TABLE "course_questions" ALTER COLUMN "id" SET DEFAULT nextval('"course_questions_id_seq"')`);
        await queryRunner.query(`ALTER TABLE "course_questions" ALTER COLUMN "id" DROP DEFAULT`);
        await queryRunner.query(`CREATE SEQUENCE IF NOT EXISTS "technologies_id_seq" OWNED BY "technologies"."id"`);
        await queryRunner.query(`ALTER TABLE "technologies" ALTER COLUMN "id" SET DEFAULT nextval('"technologies_id_seq"')`);
        await queryRunner.query(`ALTER TABLE "technologies" ALTER COLUMN "id" DROP DEFAULT`);
        await queryRunner.query(`CREATE SEQUENCE IF NOT EXISTS "mentors_id_seq" OWNED BY "mentors"."id"`);
        await queryRunner.query(`ALTER TABLE "mentors" ALTER COLUMN "id" SET DEFAULT nextval('"mentors_id_seq"')`);
        await queryRunner.query(`ALTER TABLE "mentors" ALTER COLUMN "id" DROP DEFAULT`);
        await queryRunner.query(`CREATE SEQUENCE IF NOT EXISTS "course_flow_id_seq" OWNED BY "course_flow"."id"`);
        await queryRunner.query(`ALTER TABLE "course_flow" ALTER COLUMN "id" SET DEFAULT nextval('"course_flow_id_seq"')`);
        await queryRunner.query(`ALTER TABLE "course_flow" ALTER COLUMN "id" DROP DEFAULT`);
        await queryRunner.query(`CREATE SEQUENCE IF NOT EXISTS "program_benefits_id_seq" OWNED BY "program_benefits"."id"`);
        await queryRunner.query(`ALTER TABLE "program_benefits" ALTER COLUMN "id" SET DEFAULT nextval('"program_benefits_id_seq"')`);
        await queryRunner.query(`ALTER TABLE "program_benefits" ALTER COLUMN "id" DROP DEFAULT`);
        await queryRunner.query(`CREATE SEQUENCE IF NOT EXISTS "registrations_id_seq" OWNED BY "registrations"."id"`);
        await queryRunner.query(`ALTER TABLE "registrations" ALTER COLUMN "id" SET DEFAULT nextval('"registrations_id_seq"')`);
        await queryRunner.query(`ALTER TABLE "registrations" ALTER COLUMN "id" DROP DEFAULT`);
        await queryRunner.query(`CREATE SEQUENCE IF NOT EXISTS "course_id_seq" OWNED BY "course"."id"`);
        await queryRunner.query(`ALTER TABLE "course" ALTER COLUMN "id" SET DEFAULT nextval('"course_id_seq"')`);
        await queryRunner.query(`ALTER TABLE "course" ALTER COLUMN "id" DROP DEFAULT`);
        await queryRunner.query(`CREATE SEQUENCE IF NOT EXISTS "user_answers_id_seq" OWNED BY "user_answers"."id"`);
        await queryRunner.query(`ALTER TABLE "user_answers" ALTER COLUMN "id" SET DEFAULT nextval('"user_answers_id_seq"')`);
        await queryRunner.query(`ALTER TABLE "user_answers" ALTER COLUMN "id" DROP DEFAULT`);
        await queryRunner.query(`CREATE SEQUENCE IF NOT EXISTS "answers_id_seq" OWNED BY "answers"."id"`);
        await queryRunner.query(`ALTER TABLE "answers" ALTER COLUMN "id" SET DEFAULT nextval('"answers_id_seq"')`);
        await queryRunner.query(`ALTER TABLE "answers" ALTER COLUMN "id" DROP DEFAULT`);
        await queryRunner.query(`CREATE SEQUENCE IF NOT EXISTS "questions_id_seq" OWNED BY "questions"."id"`);
        await queryRunner.query(`ALTER TABLE "questions" ALTER COLUMN "id" SET DEFAULT nextval('"questions_id_seq"')`);
        await queryRunner.query(`ALTER TABLE "questions" ALTER COLUMN "id" DROP DEFAULT`);
        await queryRunner.query(`CREATE SEQUENCE IF NOT EXISTS "scores_id_seq" OWNED BY "scores"."id"`);
        await queryRunner.query(`ALTER TABLE "scores" ALTER COLUMN "id" SET DEFAULT nextval('"scores_id_seq"')`);
        await queryRunner.query(`ALTER TABLE "scores" ALTER COLUMN "id" DROP DEFAULT`);
        await queryRunner.query(`CREATE SEQUENCE IF NOT EXISTS "quiz_progresses_id_seq" OWNED BY "quiz_progresses"."id"`);
        await queryRunner.query(`ALTER TABLE "quiz_progresses" ALTER COLUMN "id" SET DEFAULT nextval('"quiz_progresses_id_seq"')`);
        await queryRunner.query(`ALTER TABLE "quiz_progresses" ALTER COLUMN "id" DROP DEFAULT`);
        await queryRunner.query(`CREATE SEQUENCE IF NOT EXISTS "weeks_id_seq" OWNED BY "weeks"."id"`);
        await queryRunner.query(`ALTER TABLE "weeks" ALTER COLUMN "id" SET DEFAULT nextval('"weeks_id_seq"')`);
        await queryRunner.query(`ALTER TABLE "weeks" ALTER COLUMN "id" DROP DEFAULT`);
        await queryRunner.query(`CREATE SEQUENCE IF NOT EXISTS "session_progresses_id_seq" OWNED BY "session_progresses"."id"`);
        await queryRunner.query(`ALTER TABLE "session_progresses" ALTER COLUMN "id" SET DEFAULT nextval('"session_progresses_id_seq"')`);
        await queryRunner.query(`ALTER TABLE "session_progresses" ALTER COLUMN "id" DROP DEFAULT`);
        await queryRunner.query(`CREATE SEQUENCE IF NOT EXISTS "mentor_logbook_id_seq" OWNED BY "mentor_logbook"."id"`);
        await queryRunner.query(`ALTER TABLE "mentor_logbook" ALTER COLUMN "id" SET DEFAULT nextval('"mentor_logbook_id_seq"')`);
        await queryRunner.query(`ALTER TABLE "mentor_logbook" ALTER COLUMN "id" DROP DEFAULT`);
        await queryRunner.query(`CREATE SEQUENCE IF NOT EXISTS "session_id_seq" OWNED BY "session"."id"`);
        await queryRunner.query(`ALTER TABLE "session" ALTER COLUMN "id" SET DEFAULT nextval('"session_id_seq"')`);
        await queryRunner.query(`ALTER TABLE "session" ALTER COLUMN "id" DROP DEFAULT`);
        await queryRunner.query(`CREATE SEQUENCE IF NOT EXISTS "attendance_id_seq" OWNED BY "attendance"."id"`);
        await queryRunner.query(`ALTER TABLE "attendance" ALTER COLUMN "id" SET DEFAULT nextval('"attendance_id_seq"')`);
        await queryRunner.query(`ALTER TABLE "attendance" ALTER COLUMN "id" DROP DEFAULT`);
        await queryRunner.query(`CREATE SEQUENCE IF NOT EXISTS "mentor_biodata_id_seq" OWNED BY "mentor_biodata"."id"`);
        await queryRunner.query(`ALTER TABLE "mentor_biodata" ALTER COLUMN "id" SET DEFAULT nextval('"mentor_biodata_id_seq"')`);
        await queryRunner.query(`ALTER TABLE "mentor_biodata" ALTER COLUMN "id" DROP DEFAULT`);
        await queryRunner.query(`CREATE SEQUENCE IF NOT EXISTS "week_progresses_id_seq" OWNED BY "week_progresses"."id"`);
        await queryRunner.query(`ALTER TABLE "week_progresses" ALTER COLUMN "id" SET DEFAULT nextval('"week_progresses_id_seq"')`);
        await queryRunner.query(`ALTER TABLE "week_progresses" ALTER COLUMN "id" DROP DEFAULT`);
        await queryRunner.query(`CREATE SEQUENCE IF NOT EXISTS "visions_id_seq" OWNED BY "visions"."id"`);
        await queryRunner.query(`ALTER TABLE "visions" ALTER COLUMN "id" SET DEFAULT nextval('"visions_id_seq"')`);
        await queryRunner.query(`ALTER TABLE "visions" ALTER COLUMN "id" DROP DEFAULT`);
        await queryRunner.query(`CREATE SEQUENCE IF NOT EXISTS "paragraph_id_seq" OWNED BY "paragraph"."id"`);
        await queryRunner.query(`ALTER TABLE "paragraph" ALTER COLUMN "id" SET DEFAULT nextval('"paragraph_id_seq"')`);
        await queryRunner.query(`ALTER TABLE "paragraph" ALTER COLUMN "id" DROP DEFAULT`);
        await queryRunner.query(`CREATE SEQUENCE IF NOT EXISTS "mission_id_seq" OWNED BY "mission"."id"`);
        await queryRunner.query(`ALTER TABLE "mission" ALTER COLUMN "id" SET DEFAULT nextval('"mission_id_seq"')`);
        await queryRunner.query(`ALTER TABLE "mission" ALTER COLUMN "id" DROP DEFAULT`);
        await queryRunner.query(`CREATE SEQUENCE IF NOT EXISTS "image_benefit_id_seq" OWNED BY "image_benefit"."id"`);
        await queryRunner.query(`ALTER TABLE "image_benefit" ALTER COLUMN "id" SET DEFAULT nextval('"image_benefit_id_seq"')`);
        await queryRunner.query(`ALTER TABLE "image_benefit" ALTER COLUMN "id" DROP DEFAULT`);
        await queryRunner.query(`CREATE SEQUENCE IF NOT EXISTS "collaborations_id_seq" OWNED BY "collaborations"."id"`);
        await queryRunner.query(`ALTER TABLE "collaborations" ALTER COLUMN "id" SET DEFAULT nextval('"collaborations_id_seq"')`);
        await queryRunner.query(`ALTER TABLE "collaborations" ALTER COLUMN "id" DROP DEFAULT`);
        await queryRunner.query(`CREATE SEQUENCE IF NOT EXISTS "about_id_seq" OWNED BY "about"."id"`);
        await queryRunner.query(`ALTER TABLE "about" ALTER COLUMN "id" SET DEFAULT nextval('"about_id_seq"')`);
        await queryRunner.query(`ALTER TABLE "about" ALTER COLUMN "id" DROP DEFAULT`);
        await queryRunner.query(`CREATE INDEX "IDX_fd01c67d22131f7b08f5e35360" ON "category_course_types_course_type" ("categoryId") `);
        await queryRunner.query(`CREATE INDEX "IDX_ec44c43492c2851de8733701b6" ON "category_course_types_course_type" ("courseTypeId") `);
        await queryRunner.query(`CREATE INDEX "IDX_2166e744f1754b3d563e39479e" ON "mentor_technologies" ("mentorId") `);
        await queryRunner.query(`CREATE INDEX "IDX_61a698b599cce7aa90d23bd1ec" ON "mentor_technologies" ("technologiesId") `);
        await queryRunner.query(`CREATE INDEX "IDX_83be3f7b28e36967c3d3d6756f" ON "kelas_technologies" ("kelasId") `);
        await queryRunner.query(`CREATE INDEX "IDX_6604e3c7f4c53cb0645a3f8254" ON "kelas_technologies" ("technologiesId") `);
        await queryRunner.query(`ALTER TABLE "material" ADD CONSTRAINT "FK_384ac50858e585745d1c03fbb3a" FOREIGN KEY ("sessionId") REFERENCES "session"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "comments" ADD CONSTRAINT "FK_396fada4663b0ce691461219953" FOREIGN KEY ("assignment_answerId") REFERENCES "answer_task"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "answer_task" ADD CONSTRAINT "FK_7bee33a5b4ed6d30192502e8ab7" FOREIGN KEY ("taskId") REFERENCES "assignments"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "answer_task" ADD CONSTRAINT "FK_108b04110ad10adb3371b1fb7f2" FOREIGN KEY ("userId") REFERENCES "user"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "assignments" ADD CONSTRAINT "FK_11bdbd10e3a85d51c380340344c" FOREIGN KEY ("sessionId") REFERENCES "session"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "portofolios" ADD CONSTRAINT "FK_5bf14a21842b34aaab90b1e65ba" FOREIGN KEY ("userId") REFERENCES "user"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "portofolios" ADD CONSTRAINT "FK_b3f066a48d2f9d4a761d6d10f95" FOREIGN KEY ("courseId") REFERENCES "course"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "faqs" ADD CONSTRAINT "FK_fe8c81969cde9cf981451478b0e" FOREIGN KEY ("categoryId") REFERENCES "category"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "benefit_category" ADD CONSTRAINT "FK_79e63cd83523a1380f4c5bc97cb" FOREIGN KEY ("categoryId") REFERENCES "category"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "flow_category" ADD CONSTRAINT "FK_ecc0c6df5a375c832b8d94e21da" FOREIGN KEY ("categoryId") REFERENCES "category"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "superiority" ADD CONSTRAINT "FK_ba8d16a4396d40c00e1530e72cf" FOREIGN KEY ("categoryId") REFERENCES "category"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "gallery" ADD CONSTRAINT "FK_b56501212827e9cd4c3adb5e2a7" FOREIGN KEY ("categoryId") REFERENCES "category"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "installment" ADD CONSTRAINT "FK_8645d4d9ea6993bd1e904f7db78" FOREIGN KEY ("courseId") REFERENCES "course"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "payments" ADD CONSTRAINT "FK_d35cb3c13a18e1ea1705b2817b1" FOREIGN KEY ("userId") REFERENCES "user"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "payments" ADD CONSTRAINT "FK_00097d3b3147848e3585aabb433" FOREIGN KEY ("courseId") REFERENCES "course"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "payments" ADD CONSTRAINT "FK_ad038f1a0071dfcec8215129492" FOREIGN KEY ("installmentId") REFERENCES "installment"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "certificates" ADD CONSTRAINT "FK_e50e73bc3bdcfb0eb3d561f1494" FOREIGN KEY ("courseId") REFERENCES "course"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "certificates" ADD CONSTRAINT "FK_7d072194aef1ecb98664c83e861" FOREIGN KEY ("userId") REFERENCES "user"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_courses" ADD CONSTRAINT "FK_e2b16d2d170e1e994c4ed5f9476" FOREIGN KEY ("userId") REFERENCES "user"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_courses" ADD CONSTRAINT "FK_e49f8af9cda3a22a92d67973af0" FOREIGN KEY ("courseId") REFERENCES "course"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "course_questions" ADD CONSTRAINT "FK_c625383be62702e43c494c11d15" FOREIGN KEY ("courseId") REFERENCES "course"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "mentors" ADD CONSTRAINT "FK_ca235286ffe9d6a764a483d5d6d" FOREIGN KEY ("courseId") REFERENCES "course"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "alumni" ADD CONSTRAINT "FK_56b8b356cb095df75815abb32c0" FOREIGN KEY ("courseId") REFERENCES "course"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "course_flow" ADD CONSTRAINT "FK_432b6131c6b3409b965eb0026ad" FOREIGN KEY ("courseId") REFERENCES "course"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "program_benefits" ADD CONSTRAINT "FK_6aeccdff620334324d74d87134a" FOREIGN KEY ("courseId") REFERENCES "course"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "mentoring" ADD CONSTRAINT "FK_4e1a7d464b1c40255bf79e9b688" FOREIGN KEY ("courseId") REFERENCES "course"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "registrations" ADD CONSTRAINT "FK_7e5ae7aa55bb98b8b9dcbe32ca3" FOREIGN KEY ("userId") REFERENCES "user"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "registrations" ADD CONSTRAINT "FK_cf9d6bb63110657a72f858f970c" FOREIGN KEY ("courseId") REFERENCES "course"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "course" ADD CONSTRAINT "FK_c6c48d73b3b32e47e9cc1cfc4c4" FOREIGN KEY ("categoryId") REFERENCES "category"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "course" ADD CONSTRAINT "FK_b80ca1ff2ccdcc60c0a7662941c" FOREIGN KEY ("courseTypeId") REFERENCES "course_type"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_answers" ADD CONSTRAINT "FK_47a3ffddaba37b9707f93e4b140" FOREIGN KEY ("questionId") REFERENCES "questions"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_answers" ADD CONSTRAINT "FK_c4731694c2bc85d2b5acc0cee37" FOREIGN KEY ("answerId") REFERENCES "answers"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_answers" ADD CONSTRAINT "FK_23984f136e23ff9a75e7c9c3c27" FOREIGN KEY ("userId") REFERENCES "user"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "answers" ADD CONSTRAINT "FK_c38697a57844f52584abdb878d7" FOREIGN KEY ("questionId") REFERENCES "questions"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "questions" ADD CONSTRAINT "FK_35d54f06d12ea78d4842aed6b6d" FOREIGN KEY ("quizId") REFERENCES "quiz"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "scores" ADD CONSTRAINT "FK_c0508b319d67f890b4118099680" FOREIGN KEY ("userId") REFERENCES "user"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "scores" ADD CONSTRAINT "FK_6eb1536855856afba048dc38b30" FOREIGN KEY ("quizId") REFERENCES "quiz"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "quiz_progresses" ADD CONSTRAINT "FK_01ab26f101f78fb2d7d7f37bf3f" FOREIGN KEY ("userId") REFERENCES "user"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "quiz_progresses" ADD CONSTRAINT "FK_729c9e77bf8796f2dc4deda5814" FOREIGN KEY ("quizId") REFERENCES "quiz"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "quiz" ADD CONSTRAINT "FK_8a172cc59f21ff5aac9dafc781e" FOREIGN KEY ("weeksId") REFERENCES "weeks"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "weeks" ADD CONSTRAINT "FK_b9704041256eec54f93c4a03680" FOREIGN KEY ("courseId") REFERENCES "course"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "session_progresses" ADD CONSTRAINT "FK_c0459263883727f5e02bae606e3" FOREIGN KEY ("userId") REFERENCES "user"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "session_progresses" ADD CONSTRAINT "FK_72f69a4f1e4e8b13d1d2dd406d4" FOREIGN KEY ("sessionId") REFERENCES "session"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "logbook" ADD CONSTRAINT "FK_cd3e9e7600669ad4cae357455b3" FOREIGN KEY ("sessionId") REFERENCES "session"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "mentor_logbook" ADD CONSTRAINT "FK_8f2e03abc053a791f2a48a8d11b" FOREIGN KEY ("userId") REFERENCES "user"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "mentor_logbook" ADD CONSTRAINT "FK_84a133265454e62374b21725af6" FOREIGN KEY ("sessionId") REFERENCES "session"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "session" ADD CONSTRAINT "FK_d16a987478546efd1778f0fc684" FOREIGN KEY ("weeksId") REFERENCES "weeks"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "attendance" ADD CONSTRAINT "FK_466e85b813d871bfb693f443528" FOREIGN KEY ("userId") REFERENCES "user"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "attendance" ADD CONSTRAINT "FK_4b3ed2a2a22881087475bc2e597" FOREIGN KEY ("sessionId") REFERENCES "session"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "mentor_biodata" ADD CONSTRAINT "FK_16642ceba090ecc92d1bb10b43a" FOREIGN KEY ("userId") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "week_progresses" ADD CONSTRAINT "FK_746edad9baf0764eb2a53fb61f3" FOREIGN KEY ("userId") REFERENCES "user"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "week_progresses" ADD CONSTRAINT "FK_1a0133c164bf75442f7ecc11cca" FOREIGN KEY ("weekId") REFERENCES "weeks"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "category_course_types_course_type" ADD CONSTRAINT "FK_fd01c67d22131f7b08f5e353607" FOREIGN KEY ("categoryId") REFERENCES "category"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "category_course_types_course_type" ADD CONSTRAINT "FK_ec44c43492c2851de8733701b65" FOREIGN KEY ("courseTypeId") REFERENCES "course_type"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "mentor_technologies" ADD CONSTRAINT "FK_2166e744f1754b3d563e39479ec" FOREIGN KEY ("mentorId") REFERENCES "mentors"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "mentor_technologies" ADD CONSTRAINT "FK_61a698b599cce7aa90d23bd1ec7" FOREIGN KEY ("technologiesId") REFERENCES "technologies"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "kelas_technologies" ADD CONSTRAINT "FK_83be3f7b28e36967c3d3d6756f7" FOREIGN KEY ("kelasId") REFERENCES "course"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "kelas_technologies" ADD CONSTRAINT "FK_6604e3c7f4c53cb0645a3f8254a" FOREIGN KEY ("technologiesId") REFERENCES "technologies"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "kelas_technologies" DROP CONSTRAINT "FK_6604e3c7f4c53cb0645a3f8254a"`);
        await queryRunner.query(`ALTER TABLE "kelas_technologies" DROP CONSTRAINT "FK_83be3f7b28e36967c3d3d6756f7"`);
        await queryRunner.query(`ALTER TABLE "mentor_technologies" DROP CONSTRAINT "FK_61a698b599cce7aa90d23bd1ec7"`);
        await queryRunner.query(`ALTER TABLE "mentor_technologies" DROP CONSTRAINT "FK_2166e744f1754b3d563e39479ec"`);
        await queryRunner.query(`ALTER TABLE "category_course_types_course_type" DROP CONSTRAINT "FK_ec44c43492c2851de8733701b65"`);
        await queryRunner.query(`ALTER TABLE "category_course_types_course_type" DROP CONSTRAINT "FK_fd01c67d22131f7b08f5e353607"`);
        await queryRunner.query(`ALTER TABLE "week_progresses" DROP CONSTRAINT "FK_1a0133c164bf75442f7ecc11cca"`);
        await queryRunner.query(`ALTER TABLE "week_progresses" DROP CONSTRAINT "FK_746edad9baf0764eb2a53fb61f3"`);
        await queryRunner.query(`ALTER TABLE "mentor_biodata" DROP CONSTRAINT "FK_16642ceba090ecc92d1bb10b43a"`);
        await queryRunner.query(`ALTER TABLE "attendance" DROP CONSTRAINT "FK_4b3ed2a2a22881087475bc2e597"`);
        await queryRunner.query(`ALTER TABLE "attendance" DROP CONSTRAINT "FK_466e85b813d871bfb693f443528"`);
        await queryRunner.query(`ALTER TABLE "session" DROP CONSTRAINT "FK_d16a987478546efd1778f0fc684"`);
        await queryRunner.query(`ALTER TABLE "mentor_logbook" DROP CONSTRAINT "FK_84a133265454e62374b21725af6"`);
        await queryRunner.query(`ALTER TABLE "mentor_logbook" DROP CONSTRAINT "FK_8f2e03abc053a791f2a48a8d11b"`);
        await queryRunner.query(`ALTER TABLE "logbook" DROP CONSTRAINT "FK_cd3e9e7600669ad4cae357455b3"`);
        await queryRunner.query(`ALTER TABLE "session_progresses" DROP CONSTRAINT "FK_72f69a4f1e4e8b13d1d2dd406d4"`);
        await queryRunner.query(`ALTER TABLE "session_progresses" DROP CONSTRAINT "FK_c0459263883727f5e02bae606e3"`);
        await queryRunner.query(`ALTER TABLE "weeks" DROP CONSTRAINT "FK_b9704041256eec54f93c4a03680"`);
        await queryRunner.query(`ALTER TABLE "quiz" DROP CONSTRAINT "FK_8a172cc59f21ff5aac9dafc781e"`);
        await queryRunner.query(`ALTER TABLE "quiz_progresses" DROP CONSTRAINT "FK_729c9e77bf8796f2dc4deda5814"`);
        await queryRunner.query(`ALTER TABLE "quiz_progresses" DROP CONSTRAINT "FK_01ab26f101f78fb2d7d7f37bf3f"`);
        await queryRunner.query(`ALTER TABLE "scores" DROP CONSTRAINT "FK_6eb1536855856afba048dc38b30"`);
        await queryRunner.query(`ALTER TABLE "scores" DROP CONSTRAINT "FK_c0508b319d67f890b4118099680"`);
        await queryRunner.query(`ALTER TABLE "questions" DROP CONSTRAINT "FK_35d54f06d12ea78d4842aed6b6d"`);
        await queryRunner.query(`ALTER TABLE "answers" DROP CONSTRAINT "FK_c38697a57844f52584abdb878d7"`);
        await queryRunner.query(`ALTER TABLE "user_answers" DROP CONSTRAINT "FK_23984f136e23ff9a75e7c9c3c27"`);
        await queryRunner.query(`ALTER TABLE "user_answers" DROP CONSTRAINT "FK_c4731694c2bc85d2b5acc0cee37"`);
        await queryRunner.query(`ALTER TABLE "user_answers" DROP CONSTRAINT "FK_47a3ffddaba37b9707f93e4b140"`);
        await queryRunner.query(`ALTER TABLE "course" DROP CONSTRAINT "FK_b80ca1ff2ccdcc60c0a7662941c"`);
        await queryRunner.query(`ALTER TABLE "course" DROP CONSTRAINT "FK_c6c48d73b3b32e47e9cc1cfc4c4"`);
        await queryRunner.query(`ALTER TABLE "registrations" DROP CONSTRAINT "FK_cf9d6bb63110657a72f858f970c"`);
        await queryRunner.query(`ALTER TABLE "registrations" DROP CONSTRAINT "FK_7e5ae7aa55bb98b8b9dcbe32ca3"`);
        await queryRunner.query(`ALTER TABLE "mentoring" DROP CONSTRAINT "FK_4e1a7d464b1c40255bf79e9b688"`);
        await queryRunner.query(`ALTER TABLE "program_benefits" DROP CONSTRAINT "FK_6aeccdff620334324d74d87134a"`);
        await queryRunner.query(`ALTER TABLE "course_flow" DROP CONSTRAINT "FK_432b6131c6b3409b965eb0026ad"`);
        await queryRunner.query(`ALTER TABLE "alumni" DROP CONSTRAINT "FK_56b8b356cb095df75815abb32c0"`);
        await queryRunner.query(`ALTER TABLE "mentors" DROP CONSTRAINT "FK_ca235286ffe9d6a764a483d5d6d"`);
        await queryRunner.query(`ALTER TABLE "course_questions" DROP CONSTRAINT "FK_c625383be62702e43c494c11d15"`);
        await queryRunner.query(`ALTER TABLE "user_courses" DROP CONSTRAINT "FK_e49f8af9cda3a22a92d67973af0"`);
        await queryRunner.query(`ALTER TABLE "user_courses" DROP CONSTRAINT "FK_e2b16d2d170e1e994c4ed5f9476"`);
        await queryRunner.query(`ALTER TABLE "certificates" DROP CONSTRAINT "FK_7d072194aef1ecb98664c83e861"`);
        await queryRunner.query(`ALTER TABLE "certificates" DROP CONSTRAINT "FK_e50e73bc3bdcfb0eb3d561f1494"`);
        await queryRunner.query(`ALTER TABLE "payments" DROP CONSTRAINT "FK_ad038f1a0071dfcec8215129492"`);
        await queryRunner.query(`ALTER TABLE "payments" DROP CONSTRAINT "FK_00097d3b3147848e3585aabb433"`);
        await queryRunner.query(`ALTER TABLE "payments" DROP CONSTRAINT "FK_d35cb3c13a18e1ea1705b2817b1"`);
        await queryRunner.query(`ALTER TABLE "installment" DROP CONSTRAINT "FK_8645d4d9ea6993bd1e904f7db78"`);
        await queryRunner.query(`ALTER TABLE "gallery" DROP CONSTRAINT "FK_b56501212827e9cd4c3adb5e2a7"`);
        await queryRunner.query(`ALTER TABLE "superiority" DROP CONSTRAINT "FK_ba8d16a4396d40c00e1530e72cf"`);
        await queryRunner.query(`ALTER TABLE "flow_category" DROP CONSTRAINT "FK_ecc0c6df5a375c832b8d94e21da"`);
        await queryRunner.query(`ALTER TABLE "benefit_category" DROP CONSTRAINT "FK_79e63cd83523a1380f4c5bc97cb"`);
        await queryRunner.query(`ALTER TABLE "faqs" DROP CONSTRAINT "FK_fe8c81969cde9cf981451478b0e"`);
        await queryRunner.query(`ALTER TABLE "portofolios" DROP CONSTRAINT "FK_b3f066a48d2f9d4a761d6d10f95"`);
        await queryRunner.query(`ALTER TABLE "portofolios" DROP CONSTRAINT "FK_5bf14a21842b34aaab90b1e65ba"`);
        await queryRunner.query(`ALTER TABLE "assignments" DROP CONSTRAINT "FK_11bdbd10e3a85d51c380340344c"`);
        await queryRunner.query(`ALTER TABLE "answer_task" DROP CONSTRAINT "FK_108b04110ad10adb3371b1fb7f2"`);
        await queryRunner.query(`ALTER TABLE "answer_task" DROP CONSTRAINT "FK_7bee33a5b4ed6d30192502e8ab7"`);
        await queryRunner.query(`ALTER TABLE "comments" DROP CONSTRAINT "FK_396fada4663b0ce691461219953"`);
        await queryRunner.query(`ALTER TABLE "material" DROP CONSTRAINT "FK_384ac50858e585745d1c03fbb3a"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_6604e3c7f4c53cb0645a3f8254"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_83be3f7b28e36967c3d3d6756f"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_61a698b599cce7aa90d23bd1ec"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_2166e744f1754b3d563e39479e"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ec44c43492c2851de8733701b6"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_fd01c67d22131f7b08f5e35360"`);
        await queryRunner.query(`ALTER TABLE "about" ALTER COLUMN "id" SET DEFAULT nextval('tentang_id_seq')`);
        await queryRunner.query(`ALTER TABLE "about" ALTER COLUMN "id" DROP DEFAULT`);
        await queryRunner.query(`DROP SEQUENCE "about_id_seq"`);
        await queryRunner.query(`ALTER TABLE "collaborations" ALTER COLUMN "id" SET DEFAULT nextval('kerja_sama_id_seq')`);
        await queryRunner.query(`ALTER TABLE "collaborations" ALTER COLUMN "id" DROP DEFAULT`);
        await queryRunner.query(`DROP SEQUENCE "collaborations_id_seq"`);
        await queryRunner.query(`ALTER TABLE "image_benefit" ALTER COLUMN "id" SET DEFAULT nextval('gambar_benefit_id_seq')`);
        await queryRunner.query(`ALTER TABLE "image_benefit" ALTER COLUMN "id" DROP DEFAULT`);
        await queryRunner.query(`DROP SEQUENCE "image_benefit_id_seq"`);
        await queryRunner.query(`ALTER TABLE "mission" ALTER COLUMN "id" SET DEFAULT nextval('misi_id_seq')`);
        await queryRunner.query(`ALTER TABLE "mission" ALTER COLUMN "id" DROP DEFAULT`);
        await queryRunner.query(`DROP SEQUENCE "mission_id_seq"`);
        await queryRunner.query(`ALTER TABLE "paragraph" ALTER COLUMN "id" SET DEFAULT nextval('paragraf_id_seq')`);
        await queryRunner.query(`ALTER TABLE "paragraph" ALTER COLUMN "id" DROP DEFAULT`);
        await queryRunner.query(`DROP SEQUENCE "paragraph_id_seq"`);
        await queryRunner.query(`ALTER TABLE "visions" ALTER COLUMN "id" SET DEFAULT nextval('visi_id_seq')`);
        await queryRunner.query(`ALTER TABLE "visions" ALTER COLUMN "id" DROP DEFAULT`);
        await queryRunner.query(`DROP SEQUENCE "visions_id_seq"`);
        await queryRunner.query(`ALTER TABLE "week_progresses" ALTER COLUMN "id" SET DEFAULT nextval('progres_minggu_id_seq')`);
        await queryRunner.query(`ALTER TABLE "week_progresses" ALTER COLUMN "id" DROP DEFAULT`);
        await queryRunner.query(`DROP SEQUENCE "week_progresses_id_seq"`);
        await queryRunner.query(`ALTER TABLE "mentor_biodata" ALTER COLUMN "id" SET DEFAULT nextval('biodata_mentor_id_seq')`);
        await queryRunner.query(`ALTER TABLE "mentor_biodata" ALTER COLUMN "id" DROP DEFAULT`);
        await queryRunner.query(`DROP SEQUENCE "mentor_biodata_id_seq"`);
        await queryRunner.query(`ALTER TABLE "attendance" ALTER COLUMN "id" SET DEFAULT nextval('absen_id_seq')`);
        await queryRunner.query(`ALTER TABLE "attendance" ALTER COLUMN "id" DROP DEFAULT`);
        await queryRunner.query(`DROP SEQUENCE "attendance_id_seq"`);
        await queryRunner.query(`ALTER TABLE "session" ALTER COLUMN "id" SET DEFAULT nextval('pertemuan_id_seq')`);
        await queryRunner.query(`ALTER TABLE "session" ALTER COLUMN "id" DROP DEFAULT`);
        await queryRunner.query(`DROP SEQUENCE "session_id_seq"`);
        await queryRunner.query(`ALTER TABLE "mentor_logbook" ALTER COLUMN "id" SET DEFAULT nextval('logbook_mentor_id_seq')`);
        await queryRunner.query(`ALTER TABLE "mentor_logbook" ALTER COLUMN "id" DROP DEFAULT`);
        await queryRunner.query(`DROP SEQUENCE "mentor_logbook_id_seq"`);
        await queryRunner.query(`ALTER TABLE "session_progresses" ALTER COLUMN "id" SET DEFAULT nextval('progres_pertemuan_id_seq')`);
        await queryRunner.query(`ALTER TABLE "session_progresses" ALTER COLUMN "id" DROP DEFAULT`);
        await queryRunner.query(`DROP SEQUENCE "session_progresses_id_seq"`);
        await queryRunner.query(`ALTER TABLE "weeks" ALTER COLUMN "id" SET DEFAULT nextval('minggu_id_seq')`);
        await queryRunner.query(`ALTER TABLE "weeks" ALTER COLUMN "id" DROP DEFAULT`);
        await queryRunner.query(`DROP SEQUENCE "weeks_id_seq"`);
        await queryRunner.query(`ALTER TABLE "quiz_progresses" ALTER COLUMN "id" SET DEFAULT nextval('progres_quiz_id_seq')`);
        await queryRunner.query(`ALTER TABLE "quiz_progresses" ALTER COLUMN "id" DROP DEFAULT`);
        await queryRunner.query(`DROP SEQUENCE "quiz_progresses_id_seq"`);
        await queryRunner.query(`ALTER TABLE "scores" ALTER COLUMN "id" SET DEFAULT nextval('nilai_id_seq')`);
        await queryRunner.query(`ALTER TABLE "scores" ALTER COLUMN "id" DROP DEFAULT`);
        await queryRunner.query(`DROP SEQUENCE "scores_id_seq"`);
        await queryRunner.query(`ALTER TABLE "questions" ALTER COLUMN "id" SET DEFAULT nextval('pertanyaan_id_seq')`);
        await queryRunner.query(`ALTER TABLE "questions" ALTER COLUMN "id" DROP DEFAULT`);
        await queryRunner.query(`DROP SEQUENCE "questions_id_seq"`);
        await queryRunner.query(`ALTER TABLE "answers" ALTER COLUMN "id" SET DEFAULT nextval('jawaban_id_seq')`);
        await queryRunner.query(`ALTER TABLE "answers" ALTER COLUMN "id" DROP DEFAULT`);
        await queryRunner.query(`DROP SEQUENCE "answers_id_seq"`);
        await queryRunner.query(`ALTER TABLE "user_answers" ALTER COLUMN "id" SET DEFAULT nextval('jawaban_user_id_seq')`);
        await queryRunner.query(`ALTER TABLE "user_answers" ALTER COLUMN "id" DROP DEFAULT`);
        await queryRunner.query(`DROP SEQUENCE "user_answers_id_seq"`);
        await queryRunner.query(`ALTER TABLE "course" ALTER COLUMN "id" SET DEFAULT nextval('kelas_id_seq')`);
        await queryRunner.query(`ALTER TABLE "course" ALTER COLUMN "id" DROP DEFAULT`);
        await queryRunner.query(`DROP SEQUENCE "course_id_seq"`);
        await queryRunner.query(`ALTER TABLE "registrations" ALTER COLUMN "id" SET DEFAULT nextval('pendaftaran_id_seq')`);
        await queryRunner.query(`ALTER TABLE "registrations" ALTER COLUMN "id" DROP DEFAULT`);
        await queryRunner.query(`DROP SEQUENCE "registrations_id_seq"`);
        await queryRunner.query(`ALTER TABLE "program_benefits" ALTER COLUMN "id" SET DEFAULT nextval('benefit_kelas_id_seq')`);
        await queryRunner.query(`ALTER TABLE "program_benefits" ALTER COLUMN "id" DROP DEFAULT`);
        await queryRunner.query(`DROP SEQUENCE "program_benefits_id_seq"`);
        await queryRunner.query(`ALTER TABLE "course_flow" ALTER COLUMN "id" SET DEFAULT nextval('alur_kelas_id_seq')`);
        await queryRunner.query(`ALTER TABLE "course_flow" ALTER COLUMN "id" DROP DEFAULT`);
        await queryRunner.query(`DROP SEQUENCE "course_flow_id_seq"`);
        await queryRunner.query(`ALTER TABLE "mentors" ALTER COLUMN "id" SET DEFAULT nextval('mentor_id_seq')`);
        await queryRunner.query(`ALTER TABLE "mentors" ALTER COLUMN "id" DROP DEFAULT`);
        await queryRunner.query(`DROP SEQUENCE "mentors_id_seq"`);
        await queryRunner.query(`ALTER TABLE "technologies" ALTER COLUMN "id" SET DEFAULT nextval('teknologi_id_seq')`);
        await queryRunner.query(`ALTER TABLE "technologies" ALTER COLUMN "id" DROP DEFAULT`);
        await queryRunner.query(`DROP SEQUENCE "technologies_id_seq"`);
        await queryRunner.query(`ALTER TABLE "course_questions" ALTER COLUMN "id" SET DEFAULT nextval('pertanyaan_kelas_id_seq')`);
        await queryRunner.query(`ALTER TABLE "course_questions" ALTER COLUMN "id" DROP DEFAULT`);
        await queryRunner.query(`DROP SEQUENCE "course_questions_id_seq"`);
        await queryRunner.query(`ALTER TABLE "user_courses" ALTER COLUMN "id" SET DEFAULT nextval('user_kelas_id_seq')`);
        await queryRunner.query(`ALTER TABLE "user_courses" ALTER COLUMN "id" DROP DEFAULT`);
        await queryRunner.query(`DROP SEQUENCE "user_courses_id_seq"`);
        await queryRunner.query(`ALTER TABLE "certificates" ALTER COLUMN "id" SET DEFAULT nextval('sertifikat_id_seq')`);
        await queryRunner.query(`ALTER TABLE "certificates" ALTER COLUMN "id" DROP DEFAULT`);
        await queryRunner.query(`DROP SEQUENCE "certificates_id_seq"`);
        await queryRunner.query(`ALTER TABLE "payments" ALTER COLUMN "id" SET DEFAULT nextval('pembayaran_id_seq')`);
        await queryRunner.query(`ALTER TABLE "payments" ALTER COLUMN "id" DROP DEFAULT`);
        await queryRunner.query(`DROP SEQUENCE "payments_id_seq"`);
        await queryRunner.query(`ALTER TABLE "installment" ALTER COLUMN "id" SET DEFAULT nextval('cicilan_id_seq')`);
        await queryRunner.query(`ALTER TABLE "installment" ALTER COLUMN "id" DROP DEFAULT`);
        await queryRunner.query(`DROP SEQUENCE "installment_id_seq"`);
        await queryRunner.query(`ALTER TABLE "category" ALTER COLUMN "id" SET DEFAULT nextval('kategori_id_seq')`);
        await queryRunner.query(`ALTER TABLE "category" ALTER COLUMN "id" DROP DEFAULT`);
        await queryRunner.query(`DROP SEQUENCE "category_id_seq"`);
        await queryRunner.query(`ALTER TABLE "faqs" ALTER COLUMN "id" SET DEFAULT nextval('pertanyaan_umum_id_seq')`);
        await queryRunner.query(`ALTER TABLE "faqs" ALTER COLUMN "id" DROP DEFAULT`);
        await queryRunner.query(`DROP SEQUENCE "faqs_id_seq"`);
        await queryRunner.query(`ALTER TABLE "course_type" ALTER COLUMN "id" SET DEFAULT nextval('jenis_kelas_id_seq')`);
        await queryRunner.query(`ALTER TABLE "course_type" ALTER COLUMN "id" DROP DEFAULT`);
        await queryRunner.query(`DROP SEQUENCE "course_type_id_seq"`);
        await queryRunner.query(`ALTER TABLE "portofolios" ALTER COLUMN "id" SET DEFAULT nextval('portfolio_id_seq')`);
        await queryRunner.query(`ALTER TABLE "portofolios" ALTER COLUMN "id" DROP DEFAULT`);
        await queryRunner.query(`DROP SEQUENCE "portofolios_id_seq"`);
        await queryRunner.query(`ALTER TABLE "assignments" ALTER COLUMN "id" SET DEFAULT nextval('tugas_id_seq')`);
        await queryRunner.query(`ALTER TABLE "assignments" ALTER COLUMN "id" DROP DEFAULT`);
        await queryRunner.query(`DROP SEQUENCE "assignments_id_seq"`);
        await queryRunner.query(`ALTER TABLE "answer_task" ALTER COLUMN "id" SET DEFAULT nextval('jawaban_tugas_id_seq')`);
        await queryRunner.query(`ALTER TABLE "answer_task" ALTER COLUMN "id" DROP DEFAULT`);
        await queryRunner.query(`DROP SEQUENCE "answer_task_id_seq"`);
        await queryRunner.query(`ALTER TABLE "comments" ALTER COLUMN "id" SET DEFAULT nextval('komentar_id_seq')`);
        await queryRunner.query(`ALTER TABLE "comments" ALTER COLUMN "id" DROP DEFAULT`);
        await queryRunner.query(`DROP SEQUENCE "comments_id_seq"`);
        await queryRunner.query(`ALTER TABLE "material" ALTER COLUMN "id" SET DEFAULT nextval('materi_id_seq')`);
        await queryRunner.query(`ALTER TABLE "material" ALTER COLUMN "id" DROP DEFAULT`);
        await queryRunner.query(`DROP SEQUENCE "material_id_seq"`);
        await queryRunner.query(`ALTER TABLE "paragraph" RENAME COLUMN "paragraphs" TO "paragraf"`);
        await queryRunner.query(`CREATE INDEX "IDX_4f92d42fe71299ee0aa072ced3" ON "kelas_technologies" ("technologiesId") `);
        await queryRunner.query(`CREATE INDEX "IDX_77113e55b2a2023499da5b40f6" ON "kelas_technologies" ("kelasId") `);
        await queryRunner.query(`CREATE INDEX "IDX_86903a2ddb934091b9f4b21fa4" ON "mentor_technologies" ("technologiesId") `);
        await queryRunner.query(`CREATE INDEX "IDX_479f4942a07f02e2ccdea14e9b" ON "mentor_technologies" ("mentorId") `);
        await queryRunner.query(`CREATE INDEX "IDX_7b1a079b4b172de4b7d4c4c28c" ON "category_course_types_course_type" ("courseTypeId") `);
        await queryRunner.query(`CREATE INDEX "IDX_e3152cae5550f3109be808b3d8" ON "category_course_types_course_type" ("categoryId") `);
        await queryRunner.query(`ALTER TABLE "kelas_technologies" ADD CONSTRAINT "FK_4f92d42fe71299ee0aa072ced36" FOREIGN KEY ("technologiesId") REFERENCES "technologies"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "kelas_technologies" ADD CONSTRAINT "FK_77113e55b2a2023499da5b40f6e" FOREIGN KEY ("kelasId") REFERENCES "course"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "mentor_technologies" ADD CONSTRAINT "FK_86903a2ddb934091b9f4b21fa4c" FOREIGN KEY ("technologiesId") REFERENCES "technologies"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "mentor_technologies" ADD CONSTRAINT "FK_479f4942a07f02e2ccdea14e9bf" FOREIGN KEY ("mentorId") REFERENCES "mentors"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "category_course_types_course_type" ADD CONSTRAINT "FK_7b1a079b4b172de4b7d4c4c28cd" FOREIGN KEY ("courseTypeId") REFERENCES "course_type"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "category_course_types_course_type" ADD CONSTRAINT "FK_e3152cae5550f3109be808b3d81" FOREIGN KEY ("categoryId") REFERENCES "category"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "week_progresses" ADD CONSTRAINT "FK_b45ebee048a3f25dea303a1e16e" FOREIGN KEY ("weekId") REFERENCES "weeks"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "week_progresses" ADD CONSTRAINT "FK_6874c79eafd79eba86ef7e6f140" FOREIGN KEY ("userId") REFERENCES "user"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "mentor_biodata" ADD CONSTRAINT "FK_c0c27aa65c8c2919f26b8dca818" FOREIGN KEY ("userId") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "attendance" ADD CONSTRAINT "FK_557708c43c7ff517d34cd577482" FOREIGN KEY ("sessionId") REFERENCES "session"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "attendance" ADD CONSTRAINT "FK_de7d9a1aced2983b37c6d8ece55" FOREIGN KEY ("userId") REFERENCES "user"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "session" ADD CONSTRAINT "FK_77fcf90289c4a3fafca6a123100" FOREIGN KEY ("weeksId") REFERENCES "weeks"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "mentor_logbook" ADD CONSTRAINT "FK_eb81580d284633ce9e64002821d" FOREIGN KEY ("sessionId") REFERENCES "session"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "mentor_logbook" ADD CONSTRAINT "FK_26e646717dbc68eb7c083cff0dc" FOREIGN KEY ("userId") REFERENCES "user"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "logbook" ADD CONSTRAINT "FK_d4bcf4cb786b2aa92cb725e334d" FOREIGN KEY ("sessionId") REFERENCES "session"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "session_progresses" ADD CONSTRAINT "FK_d2ad48a6b17a0e2e49f0448c94b" FOREIGN KEY ("sessionId") REFERENCES "session"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "session_progresses" ADD CONSTRAINT "FK_3fdcbab09e1e09dabb560c61b8c" FOREIGN KEY ("userId") REFERENCES "user"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "weeks" ADD CONSTRAINT "FK_b69181682249c347c225f57b818" FOREIGN KEY ("courseId") REFERENCES "course"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "quiz" ADD CONSTRAINT "FK_8c7de4e4d4401526b4c9fa96807" FOREIGN KEY ("weeksId") REFERENCES "weeks"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "quiz_progresses" ADD CONSTRAINT "FK_246a41b5cf841ad8138dfbd34e0" FOREIGN KEY ("quizId") REFERENCES "quiz"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "quiz_progresses" ADD CONSTRAINT "FK_310eff946ea2abb350d260603e2" FOREIGN KEY ("userId") REFERENCES "user"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "scores" ADD CONSTRAINT "FK_b49b6e9e9b553654f33b7fd2365" FOREIGN KEY ("quizId") REFERENCES "quiz"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "scores" ADD CONSTRAINT "FK_83742310b1ddb2a60525f3e9a1f" FOREIGN KEY ("userId") REFERENCES "user"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "questions" ADD CONSTRAINT "FK_a8d79717c0dea3a67b2f37a32a3" FOREIGN KEY ("quizId") REFERENCES "quiz"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "answers" ADD CONSTRAINT "FK_3c08617c5f034c4971b4738a615" FOREIGN KEY ("questionId") REFERENCES "questions"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_answers" ADD CONSTRAINT "FK_bf422127c8fab65abcdd772e26f" FOREIGN KEY ("userId") REFERENCES "user"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_answers" ADD CONSTRAINT "FK_b50fdf127cd4e230c5acb71a905" FOREIGN KEY ("answerId") REFERENCES "answers"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_answers" ADD CONSTRAINT "FK_932636e0ba18fc9dedac59aed20" FOREIGN KEY ("questionId") REFERENCES "questions"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "course" ADD CONSTRAINT "FK_cdce265cc9c2575fd5124dfdbfa" FOREIGN KEY ("courseTypeId") REFERENCES "course_type"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "course" ADD CONSTRAINT "FK_3126d08fc69f21ced5b9a4e8223" FOREIGN KEY ("categoryId") REFERENCES "category"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "registrations" ADD CONSTRAINT "FK_422065c0547c29d258d2aafe069" FOREIGN KEY ("courseId") REFERENCES "course"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "registrations" ADD CONSTRAINT "FK_41b2fb089361275d6e5b29118c3" FOREIGN KEY ("userId") REFERENCES "user"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "mentoring" ADD CONSTRAINT "FK_08301855b186e5e01c43d4f07af" FOREIGN KEY ("courseId") REFERENCES "course"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "program_benefits" ADD CONSTRAINT "FK_a3a99572bc9e518f60697636eb7" FOREIGN KEY ("courseId") REFERENCES "course"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "course_flow" ADD CONSTRAINT "FK_da82c730e16c96240b90d0f2fca" FOREIGN KEY ("courseId") REFERENCES "course"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "alumni" ADD CONSTRAINT "FK_3dcca2bc9a925f0206e18a7baa9" FOREIGN KEY ("courseId") REFERENCES "course"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "mentors" ADD CONSTRAINT "FK_20cbfca83ecf51eadd3f4ff0032" FOREIGN KEY ("courseId") REFERENCES "course"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "course_questions" ADD CONSTRAINT "FK_2141a01e67ebab8aed7eb4b5f02" FOREIGN KEY ("courseId") REFERENCES "course"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_courses" ADD CONSTRAINT "FK_31705317a82c5c6057d36f6bca8" FOREIGN KEY ("courseId") REFERENCES "course"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_courses" ADD CONSTRAINT "FK_d23d4f7772d181abfb4ff25ac76" FOREIGN KEY ("userId") REFERENCES "user"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "certificates" ADD CONSTRAINT "FK_87bc2a5d85fed3f1a2e07d86942" FOREIGN KEY ("userId") REFERENCES "user"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "certificates" ADD CONSTRAINT "FK_4a6ffdc5c6616ca525f60898f5f" FOREIGN KEY ("courseId") REFERENCES "course"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "payments" ADD CONSTRAINT "FK_ba748cc92803680791eaab0f31d" FOREIGN KEY ("installmentId") REFERENCES "installment"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "payments" ADD CONSTRAINT "FK_ffffb1021d14348ae16f0cf7051" FOREIGN KEY ("courseId") REFERENCES "course"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "payments" ADD CONSTRAINT "FK_398ad2aad8f28ebd953cf63ba47" FOREIGN KEY ("userId") REFERENCES "user"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "installment" ADD CONSTRAINT "FK_9bc2223d71ca2cd6beb891f816c" FOREIGN KEY ("courseId") REFERENCES "course"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "gallery" ADD CONSTRAINT "FK_538f84f5155921ca47a7ee474cb" FOREIGN KEY ("categoryId") REFERENCES "category"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "superiority" ADD CONSTRAINT "FK_c34720564c7fa06cea20d4dff75" FOREIGN KEY ("categoryId") REFERENCES "category"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "flow_category" ADD CONSTRAINT "FK_e13e00da644bc6ce5180a0fb90f" FOREIGN KEY ("categoryId") REFERENCES "category"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "benefit_category" ADD CONSTRAINT "FK_e53cf775c4c30985898e10b3132" FOREIGN KEY ("categoryId") REFERENCES "category"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "faqs" ADD CONSTRAINT "FK_10c7e15fda651a1ed577cd6f88c" FOREIGN KEY ("categoryId") REFERENCES "category"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "portofolios" ADD CONSTRAINT "FK_154136295c649bd370330be4501" FOREIGN KEY ("courseId") REFERENCES "course"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "portofolios" ADD CONSTRAINT "FK_9d041c43c782a9135df1388ae16" FOREIGN KEY ("userId") REFERENCES "user"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "assignments" ADD CONSTRAINT "FK_dfe0b834578448cce571c120847" FOREIGN KEY ("sessionId") REFERENCES "session"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "answer_task" ADD CONSTRAINT "FK_d1bb0fa3821cf4a823e1be6420a" FOREIGN KEY ("userId") REFERENCES "user"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "answer_task" ADD CONSTRAINT "FK_4177e5c68c0f47895d0ade363b3" FOREIGN KEY ("taskId") REFERENCES "assignments"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "comments" ADD CONSTRAINT "FK_0d47ff3107d25a3e622d1aa9cea" FOREIGN KEY ("assignment_answerId") REFERENCES "answer_task"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "material" ADD CONSTRAINT "FK_fb825ba8148529711b3d0052cd6" FOREIGN KEY ("sessionId") REFERENCES "session"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
    }

}
