import { MigrationInterface, QueryRunner } from 'typeorm';

/**
 * Skema dasar - HANYA untuk basis data yang benar-benar kosong.
 *
 * KENAPA INI ADA
 *
 * Basis data ini mencatat 29 migrasi, tetapi hanya 18 berkasnya yang masih
 * ada (7 aktif + 11 di `_archive`). Sebelas migrasi yang MEMBUAT skema
 * dasarnya sudah tidak punya berkas sama sekali. Akibatnya, sampai migrasi
 * ini ada, basis data ini TIDAK BISA DIBANGUN DARI NOL:
 *
 *   RefactorDatabaseServer1788100000000  -> lolos, tetapi seluruh penjaganya
 *                                           melewat karena tidak ada tabel
 *   ConvertIdsToUuid1788300000000        -> berhenti dengan pesan "tidak
 *                                           menemukan satu pun tabel dengan
 *                                           primary key integer"
 *
 * Migrasi ini menutup lubang itu: isinya dihasilkan `migration:generate` dari
 * entity terhadap basis data kosong, jadi ia menggambarkan skema yang persis
 * sama dengan yang dipakai kode hari ini.
 *
 * PENJAGANYA
 *
 * Kalau tabel `course` sudah ada, migrasi ini TIDAK melakukan apa pun - ia
 * hanya tercatat supaya basis data yang sudah jalan tidak mencoba membangun
 * ulang apa yang sudah ada. Jadi aman dijalankan pada basis data lama maupun
 * basis data kosong.
 *
 * `down()` sengaja TIDAK menghapus apa pun. Membalikkan skema dasar berarti
 * menghapus seluruh basis data, dan itu tidak boleh terjadi karena seseorang
 * salah ketik `migration:revert`.
 *
 * Timestamp-nya sengaja lebih kecil dari migrasi lain supaya ia jalan paling
 * awal pada basis data kosong.
 */
export class BaselineSchema1787999999999 implements MigrationInterface {
  name = 'BaselineSchema1787999999999';

  public async up(queryRunner: QueryRunner): Promise<void> {
    const [row] = await queryRunner.query(
      `SELECT to_regclass('public.course') IS NOT NULL AS provisioned`,
    );
    if (row?.provisioned) {
      // Basis data ini sudah punya skemanya dari riwayat migrasi lama.
      return;
    }

    await queryRunner.query(`CREATE EXTENSION IF NOT EXISTS "uuid-ossp"`);

    // Catatan: hasil `migration:generate` memancarkan CREATE TYPE sekali per
    // KOLOM, bukan per tipe. Karena beberapa enum sengaja dipakai ulang lintas
    // tabel (lihat migrasi 1788700000000), duplikatnya dibuang - Postgres tidak
    // punya CREATE TYPE IF NOT EXISTS.
await queryRunner.query(`CREATE TABLE "biodata" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "fullName" character varying, "no" character varying NOT NULL, "gender" character varying, "city" character varying, "education" character varying, "studyProgram" character varying, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "userId" uuid NOT NULL, CONSTRAINT "REL_477a671c8b8c738777b03a2c60" UNIQUE ("userId"), CONSTRAINT "PK_5e0c867deda29cac97995e52bcc" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "course_type" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "nameClassesType" character varying, "icon" character varying NOT NULL, "description" jsonb, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_ed75c33d531547ed8b0164d75b2" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "faqs" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "question" jsonb, "answer" jsonb, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "categoryId" uuid, CONSTRAINT "PK_2ddf4f2c910f8e8fa2663a67bf0" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "benefit_category" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "icon" character varying NOT NULL, "title" jsonb, "description" jsonb, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "categoryId" uuid, CONSTRAINT "PK_0b59e103d6fcaa86271bc7bf5b2" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."gallery_no_enum" AS ENUM('1', '2', '3', '4', '5', '6', '7')`);
        await queryRunner.query(`CREATE TABLE "gallery" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "filePath" character varying NOT NULL, "title" character varying NOT NULL, "description" character varying, "no" "public"."gallery_no_enum" NOT NULL, "categoryId" uuid, CONSTRAINT "PK_65d7a1ef91ddafb3e7071b188a0" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."category_type_enum" AS ENUM('Special Program', 'Paid Program', 'Free Program')`);
        await queryRunner.query(`CREATE TABLE "category" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying, "text" jsonb, "icon" character varying NOT NULL, "hero_section_image" character varying, "description" jsonb, "contact" character varying, "type" "public"."category_type_enum", "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_9c4e4a89e3674fc9f382d733f03" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."installment_month_enum" AS ENUM('3')`);
        await queryRunner.query(`CREATE TABLE "installment" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "downPayment" integer NOT NULL, "price" jsonb NOT NULL, "month" "public"."installment_month_enum" NOT NULL, "dueDates" date array NOT NULL DEFAULT '{}', "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "courseId" uuid, CONSTRAINT "PK_c79b5b68e8b6293a0210ce7dbda" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "invoice" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "xendit_invoice_id" character varying, "xendit_invoice_url" character varying, "subtotal" numeric(12,2), "discount_amount" numeric(12,2) DEFAULT '0', "final_total" numeric(12,2), "payment_method" character varying, "paid_at" TIMESTAMP, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "paymentId" uuid, CONSTRAINT "REL_03ccf846238db85401525e07cd" UNIQUE ("paymentId"), CONSTRAINT "PK_15d25c200d9bcd8a33f698daf18" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."payments_referalsource_enum" AS ENUM('Instagram', 'TikTok', 'LinkedIn', 'Friends', 'University', 'WhatsApp Group', 'Webinar/Event', 'Website', 'Other')`);
        await queryRunner.query(`CREATE TYPE "public"."payments_process_enum" AS ENUM('approved', 'process', 'rejected')`);
        await queryRunner.query(`CREATE TYPE "public"."payments_current_status_enum" AS ENUM('University Student', 'Fresh Graduate', 'Job Seeker', 'Employee', 'Freelancer', 'Entrepreneur', 'Other')`);
        await queryRunner.query(`CREATE TABLE "payments" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "file" character varying, "no" character varying, "referalSource" "public"."payments_referalsource_enum", "process" "public"."payments_process_enum" NOT NULL DEFAULT 'rejected', "current_status" "public"."payments_current_status_enum", "user_fullname" character varying, "user_email" character varying, "user_no" character varying, "attend_program" boolean, "dpPaidAt" TIMESTAMP, "reminderSentMonths" jsonb DEFAULT '[]', "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "userId" uuid, "courseId" uuid, "installmentId" uuid, CONSTRAINT "PK_197ab7af18c93fbb0c9b28b4a59" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."material_filetype_enum" AS ENUM('video', 'pdf', 'ppt')`);
        await queryRunner.query(`CREATE TABLE "syllabus_material" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "title" character varying NOT NULL, "file" character varying NOT NULL, "fileType" "public"."material_filetype_enum" NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "syllabusId" uuid NOT NULL, CONSTRAINT "PK_2d030c346c820b3ec60e00c51d8" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_syllabus_material_syllabus" ON "syllabus_material" ("syllabusId") `);
        await queryRunner.query(`CREATE TABLE "syllabus_comment" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "comment" character varying NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "answerId" uuid NOT NULL, CONSTRAINT "PK_c8bf7a084fc8df7c1787a90c273" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_syllabus_comment_answer" ON "syllabus_comment" ("answerId") `);
        await queryRunner.query(`CREATE TYPE "public"."answer_task_process_enum" AS ENUM('approved', 'process', 'rejected')`);
        await queryRunner.query(`CREATE TABLE "syllabus_answer_task" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "file" character varying NOT NULL, "process" "public"."answer_task_process_enum" NOT NULL DEFAULT 'rejected', "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "taskId" uuid NOT NULL, "userId" uuid NOT NULL, CONSTRAINT "UQ_syllabus_answer_task_task_user" UNIQUE ("taskId", "userId"), CONSTRAINT "PK_2418a19c1a033ca66954ba85691" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_syllabus_answer_task_user" ON "syllabus_answer_task" ("userId") `);
        await queryRunner.query(`CREATE TABLE "syllabus_assignment" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "title" character varying NOT NULL, "file" character varying NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "syllabusId" uuid NOT NULL, CONSTRAINT "PK_b550f8eff3f9525ac5a00ffe9e3" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_syllabus_assignment_syllabus" ON "syllabus_assignment" ("syllabusId") `);
        await queryRunner.query(`CREATE TYPE "public"."logbook_process_enum" AS ENUM('approved', 'process', 'rejected')`);
        await queryRunner.query(`CREATE TABLE "syllabus_logbook" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "activity" character varying, "activity_details" character varying, "documentation" character varying, "obstacles" character varying, "other_documentation" character varying, "process" "public"."logbook_process_enum" NOT NULL DEFAULT 'rejected', "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "syllabusId" uuid NOT NULL, "userId" uuid NOT NULL, CONSTRAINT "PK_96063270005a2d8dd0cf604324f" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_syllabus_logbook_user" ON "syllabus_logbook" ("userId", "syllabusId") `);
        await queryRunner.query(`CREATE TABLE "syllabus_progress" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "completedAt" TIMESTAMP, "logbookOk" boolean NOT NULL DEFAULT false, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "syllabusId" uuid NOT NULL, "userId" uuid NOT NULL, CONSTRAINT "UQ_syllabus_progress_syllabus_user" UNIQUE ("syllabusId", "userId"), CONSTRAINT "PK_382f47f14ffb19c23f43001b3e2" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_syllabus_progress_user" ON "syllabus_progress" ("userId") `);
        await queryRunner.query(`CREATE TABLE "syllabus" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "order" integer NOT NULL, "title" character varying NOT NULL, "description" text, "is_final" boolean NOT NULL DEFAULT false, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "courseId" uuid NOT NULL, CONSTRAINT "UQ_syllabus_course_order" UNIQUE ("courseId", "order"), CONSTRAINT "PK_5205bdbdb2d719615ccf5eabfb5" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_syllabus_course" ON "syllabus" ("courseId", "order") `);
        await queryRunner.query(`CREATE TABLE "user_answers" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "questionId" uuid, "answerId" uuid, "userId" uuid, CONSTRAINT "PK_08977c1a2a5f1b8b472dbd87d04" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "answers" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "answer" character varying NOT NULL, "isCorrect" boolean NOT NULL DEFAULT false, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "questionId" uuid, CONSTRAINT "PK_9c32cec6c71e06da0254f2226c6" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "questions" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "questionText" character varying NOT NULL, "image" character varying, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "quizId" uuid, CONSTRAINT "PK_08a6d4b0f49ff300bf3a0ca60ac" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "scores" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "score" integer NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "userId" uuid, "quizId" uuid, CONSTRAINT "PK_c36917e6f26293b91d04b8fd521" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "quiz_progresses" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "process" boolean NOT NULL DEFAULT false, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "userId" uuid, "quizId" uuid, CONSTRAINT "PK_0a175ba8fe57d1f7096bd128733" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "quiz" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "quiz_name" character varying NOT NULL, "minimum_score" integer NOT NULL, "duration" integer NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "courseId" uuid, "weeksId" uuid, CONSTRAINT "PK_422d974e7217414e029b3e641d0" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_quiz_course" ON "quiz" ("courseId") `);
        await queryRunner.query(`CREATE TABLE "certificates" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "certificate_file" character varying NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "courseId" uuid, "userId" uuid, CONSTRAINT "PK_e4c7e31e2144300bea7d89eb165" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "user_courses" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "progress" boolean NOT NULL DEFAULT false, "userId" uuid, "courseId" uuid, CONSTRAINT "PK_0802c48ad82a16822bd7041154a" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "course_questions" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "question" jsonb, "answer" jsonb, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "courseId" uuid, CONSTRAINT "PK_d7392fe407562e5e5b1cf1a3488" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "technologies" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying NOT NULL, "svg" text, "imgUrl" character varying, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_9a97465b79568f00becacdd4e4a" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "mentors" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying NOT NULL, "position" jsonb, "linkedin" character varying NOT NULL, "profile" character varying NOT NULL, "description" jsonb, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "courseId" uuid, CONSTRAINT "PK_67a614446eab992e4d0580afebf" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "alumni" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "profile" character varying NOT NULL, "name" jsonb, "message" jsonb, "currentPosition" jsonb, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "courseId" uuid, CONSTRAINT "PK_6947d90e8215d18adec98799895" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "course_flow" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "sequence" integer NOT NULL, "title" jsonb, "content" jsonb, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "courseId" uuid, CONSTRAINT "PK_1b2b49c6e5c5b8f2f28fb46c9df" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "program_benefits" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "benefit" jsonb, "description" jsonb, "icon" character varying NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "courseId" uuid, CONSTRAINT "PK_e14b096da733107a463c60a103e" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "participants" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "title" jsonb, "description" jsonb, "icon" character varying NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "courseId" uuid, CONSTRAINT "PK_1cda06c31eec1c95b3365a0283f" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "mentoring" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "userId" uuid, "courseId" uuid, CONSTRAINT "PK_7c4e8636242b5454992c004899b" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."registrations_process_enum" AS ENUM('approved', 'process', 'rejected')`);
        await queryRunner.query(`CREATE TYPE "public"."registrations_current_status_enum" AS ENUM('University Student', 'Fresh Graduate', 'Job Seeker', 'Employee', 'Freelancer', 'Entrepreneur', 'Other')`);
        await queryRunner.query(`CREATE TYPE "public"."registrations_referal_source_enum" AS ENUM('Instagram', 'TikTok', 'LinkedIn', 'Friends', 'University', 'WhatsApp Group', 'Webinar/Event', 'Website', 'Other')`);
        await queryRunner.query(`CREATE TABLE "registrations" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "file" character varying, "process" "public"."registrations_process_enum" NOT NULL DEFAULT 'rejected', "user_fullname" character varying, "user_email" character varying, "user_no" character varying, "current_status" "public"."registrations_current_status_enum", "attend_program" boolean, "referal_source" "public"."registrations_referal_source_enum", "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "userId" uuid, "courseId" uuid, CONSTRAINT "PK_6013e724d7b22929da9cd7282d1" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."voucher_type_enum" AS ENUM('free', 'discount')`);
        await queryRunner.query(`CREATE TABLE "voucher" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "code_voucher" character varying NOT NULL, "type" "public"."voucher_type_enum" NOT NULL, "percent" double precision, "active" boolean NOT NULL DEFAULT true, "url_code" uuid NOT NULL DEFAULT uuid_generate_v4(), "allowed_user_ids" json, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_0f096105ca8411f6f815ef3d6b9" UNIQUE ("code_voucher"), CONSTRAINT "UQ_ca236f1dbd4aaf11b317ea67f62" UNIQUE ("url_code"), CONSTRAINT "PK_677ae75f380e81c2f103a57ffaf" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."course_method_enum" AS ENUM('online', 'offline')`);
        await queryRunner.query(`CREATE TYPE "public"."course_program_type_enum" AS ENUM('bootcamp', 'non_bootcamp', 'lpk')`);
        await queryRunner.query(`CREATE TYPE "public"."course_process_enum" AS ENUM('approved', 'process', 'rejected')`);
        await queryRunner.query(`CREATE TABLE "course" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying NOT NULL, "description" jsonb, "group" character varying NOT NULL, "image" character varying NOT NULL, "price" integer, "promo" integer, "locationLink" character varying, "locations" jsonb, "method" "public"."course_method_enum" NOT NULL, "criteriaId" jsonb, "criteriaEn" jsonb, "criteriaJa" jsonb, "launch" boolean NOT NULL DEFAULT false, "date_registration" TIMESTAMP, "program_type" "public"."course_program_type_enum" NOT NULL DEFAULT 'bootcamp', "logbook_enabled" boolean NOT NULL DEFAULT true, "process" "public"."course_process_enum" NOT NULL DEFAULT 'rejected', "materialsId" jsonb, "materialsEn" jsonb, "materialsJa" jsonb, "learningTargetsId" jsonb, "learningTargetsEn" jsonb, "learningTargetsJa" jsonb, "quota" integer, "form" character varying, "checkPaid" boolean NOT NULL DEFAULT false, "month" integer, "day" integer, "startDate" TIMESTAMP NOT NULL, "startEnd" TIMESTAMP NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "time_start" TIME, "time_end" TIME, "categoryId" uuid, "courseTypeId" uuid, CONSTRAINT "PK_bf95180dd756fd204fb01ce4916" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "portofolios" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "image" jsonb NOT NULL, "title" character varying NOT NULL, "content" text NOT NULL, "contentHtml" text NOT NULL, "description" character varying NOT NULL, "link" character varying NOT NULL, "views" integer NOT NULL DEFAULT '0', "likes" integer NOT NULL DEFAULT '0', "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "userId" uuid, "courseId" uuid, CONSTRAINT "PK_7925cc12f40f096a486210b6866" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "mentor_biodata" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "role" character varying NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "userId" uuid, CONSTRAINT "REL_16642ceba090ecc92d1bb10b43" UNIQUE ("userId"), CONSTRAINT "PK_0d888f6efb571e494892349a042" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "assignments" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "title" character varying NOT NULL, "file" character varying NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "sessionId" uuid, CONSTRAINT "PK_c54ca359535e0012b04dcbd80ee" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "comments" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "comment" character varying NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "assignment_answerId" uuid, CONSTRAINT "PK_8bf68bc960f2b69e818bdb90dcb" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "answer_task" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "file" character varying NOT NULL, "process" "public"."answer_task_process_enum" NOT NULL DEFAULT 'rejected', "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "taskId" uuid, "userId" uuid, CONSTRAINT "PK_d5079d16156e89f5390de359e12" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "logbook" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "activity" character varying, "activity_details" character varying, "documentation" character varying, "process" "public"."logbook_process_enum" NOT NULL DEFAULT 'rejected', "obstacles" character varying, "other_documentation" character varying, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "userId" uuid, "sessionId" uuid, CONSTRAINT "PK_bf9f4ef320dc561b0d9a63b1853" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "week_progresses" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "quiz" boolean NOT NULL DEFAULT false, "process" boolean NOT NULL DEFAULT false, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "userId" uuid, "weekId" uuid, CONSTRAINT "PK_ce0ecb286461d3ea324245977ad" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "session_progresses" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "logbook" boolean NOT NULL DEFAULT false, "isAttended" boolean NOT NULL DEFAULT false, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "userId" uuid, "sessionId" uuid, CONSTRAINT "PK_1c633f1f1421465a9f20dc0fe7c" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "mentor_logbook" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "activity" character varying NOT NULL, "activityDetail" character varying NOT NULL, "documentation" character varying NOT NULL, "obstacle" character varying NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "userId" uuid, "sessionId" uuid, CONSTRAINT "PK_404b9cc8c1ef98f0812f750ccaa" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "user_activity" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "userId" uuid NOT NULL, "sessionId" character varying, "loginAt" TIMESTAMP NOT NULL, "lastSeenAt" TIMESTAMP NOT NULL, "currentCourseId" uuid, "activityLabel" character varying, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_c8d8d7cfc6e3433e725339c952b" UNIQUE ("userId"), CONSTRAINT "PK_daec6d19443689bda7d7785dff5" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."activity_log_eventtype_enum" AS ENUM('login', 'logout', 'expired')`);
        await queryRunner.query(`CREATE TABLE "activity_log" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "userId" uuid NOT NULL, "eventType" "public"."activity_log_eventtype_enum" NOT NULL, "eventAt" TIMESTAMP NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_067d761e2956b77b14e534fd6f1" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."user_role_enum" AS ENUM('super_admin', 'admin', 'user')`);
        await queryRunner.query(`CREATE TABLE "user" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "username" character varying NOT NULL, "email" character varying NOT NULL, "password" character varying NOT NULL, "profile" character varying, "role" "public"."user_role_enum" NOT NULL DEFAULT 'user', "resetPasswordToken" character varying, "resetPasswordExpires" TIMESTAMP, "isVerified" boolean DEFAULT false, "verificationToken" character varying, "verificationTokenExpires" TIMESTAMP, "countdownQuiz" TIMESTAMP, "quizStart" boolean DEFAULT false, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_e12875dfb3b1d92d7d7c5377e22" UNIQUE ("email"), CONSTRAINT "PK_cace4a159ff9f2512dd42373760" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."attendance_status_enum" AS ENUM('permission', 'present', 'sick', 'absent', 'no_information')`);
        await queryRunner.query(`CREATE TABLE "attendance" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "status" "public"."attendance_status_enum" NOT NULL DEFAULT 'no_information', "attendanceTime" TIMESTAMP NOT NULL, "notes" character varying NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "userId" uuid, "sessionId" uuid, CONSTRAINT "PK_ee0ffe42c1f1a01e72b725c0cb2" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "material" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "title" character varying NOT NULL, "file" character varying NOT NULL, "fileType" "public"."material_filetype_enum" NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "sessionId" uuid, CONSTRAINT "PK_0343d0d577f3effc2054cbaca7f" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "session" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "topic" character varying, "sessionOrder" integer, "date" TIMESTAMP, "location" character varying, "start_time" TIME, "end_time" TIME, "is_final" boolean NOT NULL DEFAULT false, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "weeksId" uuid, CONSTRAINT "PK_f55da76ac1c3ac420f444d2ff11" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "weeks" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "week_number" integer NOT NULL, "description" character varying NOT NULL, "is_final" boolean NOT NULL DEFAULT false, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "courseId" uuid, CONSTRAINT "PK_003488ee2ca80ef0c85a02a8065" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "visions" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "visions" jsonb, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_b0b8a846c4ea60ba098c7e426d5" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "value" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "title" jsonb, "description" jsonb, "icon" character varying NOT NULL, "valueOrder" integer NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_0af87b1623a34dd5357bfdb38a4" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "team_leads" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "profile" character varying NOT NULL, "name" character varying NOT NULL, "position" jsonb, "description" jsonb, "instagram" character varying NOT NULL, "linkedin" character varying NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_fd18dad91eb7dcd6707fdb4fe9f" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "team" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "profile" character varying NOT NULL, "name" character varying, "teamOrder" integer, "position" jsonb, "linkedin" character varying NOT NULL, "instagram" character varying, "description" jsonb, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_f57d8293406df4af348402e4b74" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "social" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "linkedin" character varying NOT NULL, "instagram" character varying NOT NULL, "youtube" character varying NOT NULL, "videoYoutube" character varying, "linkForm" character varying, "email" character varying NOT NULL, "address" character varying NOT NULL, "number" character varying NOT NULL, "linkAddress" text NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_645aa1cff2b9f7b0e3e73d66b4d" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "category_partner" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "category" character varying NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_5240208e5c7fe6e874ab0bf1696" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "partner" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "image" character varying NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "categoryPartnerId" uuid NOT NULL, CONSTRAINT "PK_8f34ff11ddd5459eacbfacd48ca" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "paragraph" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "paragraphs" jsonb, "paragraphOrder" integer NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_c4000792b02bf27771092e4e3c7" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "mission" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "missionOrder" integer NOT NULL, "content" jsonb, "items" jsonb, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_54f1391034bc7dd30666dee0d4c" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."installment_payments_status_enum" AS ENUM('process', 'approved', 'rejected')`);
        await queryRunner.query(`CREATE TABLE "installment_payments" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "month" integer NOT NULL, "amount" numeric(12,2), "no" character varying, "xendit_invoice_id" character varying, "xendit_invoice_url" character varying, "status" "public"."installment_payments_status_enum" NOT NULL DEFAULT 'process', "paidAt" TIMESTAMP, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "paymentId" uuid NOT NULL, CONSTRAINT "PK_067d1ad6172df1562048fb773be" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "info" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "title" jsonb, "text" jsonb, "icon" character varying NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_687dc5e25f4f1ee093a45b68bb7" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "header" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "title" character varying NOT NULL, "text" character varying NOT NULL, "image" character varying NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_007a885cf40484eb750d0355339" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "faq" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "question" jsonb, "answer" jsonb, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_d6f5a52b1a96dd8d0591f9fbc47" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "experience" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "content" jsonb, "details" jsonb, "experienceOrder" integer, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_5e8d5a534100e1b17ee2efa429a" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "commitment" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "title" jsonb, "description" jsonb, "icon" character varying NOT NULL, "commitmentOrder" integer, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_7a0899978d100f72269b3045d7e" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."benefit_no_enum" AS ENUM('1', '2', '3', '4', '5')`);
        await queryRunner.query(`CREATE TABLE "benefit" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "title" jsonb, "description" jsonb, "icon" character varying NOT NULL, "no" "public"."benefit_no_enum" NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_c024dccb30e6f4702adffe884d1" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "background" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "content" jsonb, "details" jsonb, "backgroundOrder" integer, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_7271b4d2e4bd0f68b3fdb5c090a" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "award" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "content" jsonb, "details" jsonb, "awardOrder" integer, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_e887e4e69663925ebb60d3a7775" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "about" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "title" jsonb, "text" jsonb, "image" character varying NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_e7b581a8a74d0a2ea3aa53226ee" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "category_course_types" ("categoryId" uuid NOT NULL, "courseTypeId" uuid NOT NULL, CONSTRAINT "PK_46e94a842f30015abd52933882a" PRIMARY KEY ("categoryId", "courseTypeId"))`);
        await queryRunner.query(`CREATE INDEX "IDX_9cb9d2737820c50a036bd00e6e" ON "category_course_types" ("categoryId") `);
        await queryRunner.query(`CREATE INDEX "IDX_6ce84ef379233fa1a44b31f3c1" ON "category_course_types" ("courseTypeId") `);
        await queryRunner.query(`CREATE TABLE "mentor_technologies" ("mentorId" uuid NOT NULL, "technologiesId" uuid NOT NULL, CONSTRAINT "PK_82c7ed8fc4483ede9175b26ace4" PRIMARY KEY ("mentorId", "technologiesId"))`);
        await queryRunner.query(`CREATE INDEX "IDX_2166e744f1754b3d563e39479e" ON "mentor_technologies" ("mentorId") `);
        await queryRunner.query(`CREATE INDEX "IDX_61a698b599cce7aa90d23bd1ec" ON "mentor_technologies" ("technologiesId") `);
        await queryRunner.query(`CREATE TABLE "voucher_programs" ("voucherId" uuid NOT NULL, "courseId" uuid NOT NULL, CONSTRAINT "PK_60da304b510577328bb2b2fe0b2" PRIMARY KEY ("voucherId", "courseId"))`);
        await queryRunner.query(`CREATE INDEX "IDX_3f413ec454a7f2f52509d492d0" ON "voucher_programs" ("voucherId") `);
        await queryRunner.query(`CREATE INDEX "IDX_878fddcdb2fd31b3b5a17ac534" ON "voucher_programs" ("courseId") `);
        await queryRunner.query(`CREATE TABLE "course_technologies" ("courseId" uuid NOT NULL, "technologyId" uuid NOT NULL, CONSTRAINT "PK_fdd8c4d3eb5f2365168538d4406" PRIMARY KEY ("courseId", "technologyId"))`);
        await queryRunner.query(`CREATE INDEX "IDX_7443437646b916f32e640d1b29" ON "course_technologies" ("courseId") `);
        await queryRunner.query(`CREATE INDEX "IDX_0ce505f9c9052d14d4d4cf00b1" ON "course_technologies" ("technologyId") `);
        await queryRunner.query(`ALTER TABLE "biodata" ADD CONSTRAINT "FK_477a671c8b8c738777b03a2c607" FOREIGN KEY ("userId") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "faqs" ADD CONSTRAINT "FK_fe8c81969cde9cf981451478b0e" FOREIGN KEY ("categoryId") REFERENCES "category"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "benefit_category" ADD CONSTRAINT "FK_79e63cd83523a1380f4c5bc97cb" FOREIGN KEY ("categoryId") REFERENCES "category"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "gallery" ADD CONSTRAINT "FK_b56501212827e9cd4c3adb5e2a7" FOREIGN KEY ("categoryId") REFERENCES "category"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "installment" ADD CONSTRAINT "FK_8645d4d9ea6993bd1e904f7db78" FOREIGN KEY ("courseId") REFERENCES "course"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "invoice" ADD CONSTRAINT "FK_03ccf846238db85401525e07cd2" FOREIGN KEY ("paymentId") REFERENCES "payments"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "payments" ADD CONSTRAINT "FK_d35cb3c13a18e1ea1705b2817b1" FOREIGN KEY ("userId") REFERENCES "user"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "payments" ADD CONSTRAINT "FK_00097d3b3147848e3585aabb433" FOREIGN KEY ("courseId") REFERENCES "course"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "payments" ADD CONSTRAINT "FK_ad038f1a0071dfcec8215129492" FOREIGN KEY ("installmentId") REFERENCES "installment"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "syllabus_material" ADD CONSTRAINT "FK_ba6bac3a5bd4aa1ae63c4d19109" FOREIGN KEY ("syllabusId") REFERENCES "syllabus"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "syllabus_comment" ADD CONSTRAINT "FK_44efd0cdf2c5324c55ea9a1b843" FOREIGN KEY ("answerId") REFERENCES "syllabus_answer_task"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "syllabus_answer_task" ADD CONSTRAINT "FK_65783e2d1f137231808b2e896d0" FOREIGN KEY ("taskId") REFERENCES "syllabus_assignment"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "syllabus_answer_task" ADD CONSTRAINT "FK_1705b1952e2df3975a695479c0b" FOREIGN KEY ("userId") REFERENCES "user"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "syllabus_assignment" ADD CONSTRAINT "FK_0d1b23153a81d54aab77c093941" FOREIGN KEY ("syllabusId") REFERENCES "syllabus"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "syllabus_logbook" ADD CONSTRAINT "FK_c05c16d2718c1f64313096a0b78" FOREIGN KEY ("syllabusId") REFERENCES "syllabus"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "syllabus_logbook" ADD CONSTRAINT "FK_ca7a58fcbe310bf69d5b19c4e3b" FOREIGN KEY ("userId") REFERENCES "user"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "syllabus_progress" ADD CONSTRAINT "FK_e486ec5c9425f8fad0473d5e748" FOREIGN KEY ("syllabusId") REFERENCES "syllabus"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "syllabus_progress" ADD CONSTRAINT "FK_a2ed86a25c3755309cca1527171" FOREIGN KEY ("userId") REFERENCES "user"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "syllabus" ADD CONSTRAINT "FK_7e3341205b518cbd98380b20b16" FOREIGN KEY ("courseId") REFERENCES "course"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_answers" ADD CONSTRAINT "FK_47a3ffddaba37b9707f93e4b140" FOREIGN KEY ("questionId") REFERENCES "questions"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_answers" ADD CONSTRAINT "FK_c4731694c2bc85d2b5acc0cee37" FOREIGN KEY ("answerId") REFERENCES "answers"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_answers" ADD CONSTRAINT "FK_23984f136e23ff9a75e7c9c3c27" FOREIGN KEY ("userId") REFERENCES "user"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "answers" ADD CONSTRAINT "FK_c38697a57844f52584abdb878d7" FOREIGN KEY ("questionId") REFERENCES "questions"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "questions" ADD CONSTRAINT "FK_35d54f06d12ea78d4842aed6b6d" FOREIGN KEY ("quizId") REFERENCES "quiz"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "scores" ADD CONSTRAINT "FK_c0508b319d67f890b4118099680" FOREIGN KEY ("userId") REFERENCES "user"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "scores" ADD CONSTRAINT "FK_6eb1536855856afba048dc38b30" FOREIGN KEY ("quizId") REFERENCES "quiz"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "quiz_progresses" ADD CONSTRAINT "FK_01ab26f101f78fb2d7d7f37bf3f" FOREIGN KEY ("userId") REFERENCES "user"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "quiz_progresses" ADD CONSTRAINT "FK_729c9e77bf8796f2dc4deda5814" FOREIGN KEY ("quizId") REFERENCES "quiz"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "quiz" ADD CONSTRAINT "FK_f74ae73a766eea8e0dfb09816ba" FOREIGN KEY ("courseId") REFERENCES "course"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "quiz" ADD CONSTRAINT "FK_8a172cc59f21ff5aac9dafc781e" FOREIGN KEY ("weeksId") REFERENCES "weeks"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "certificates" ADD CONSTRAINT "FK_e50e73bc3bdcfb0eb3d561f1494" FOREIGN KEY ("courseId") REFERENCES "course"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "certificates" ADD CONSTRAINT "FK_7d072194aef1ecb98664c83e861" FOREIGN KEY ("userId") REFERENCES "user"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_courses" ADD CONSTRAINT "FK_e2b16d2d170e1e994c4ed5f9476" FOREIGN KEY ("userId") REFERENCES "user"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_courses" ADD CONSTRAINT "FK_e49f8af9cda3a22a92d67973af0" FOREIGN KEY ("courseId") REFERENCES "course"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "course_questions" ADD CONSTRAINT "FK_c625383be62702e43c494c11d15" FOREIGN KEY ("courseId") REFERENCES "course"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "mentors" ADD CONSTRAINT "FK_ca235286ffe9d6a764a483d5d6d" FOREIGN KEY ("courseId") REFERENCES "course"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "alumni" ADD CONSTRAINT "FK_56b8b356cb095df75815abb32c0" FOREIGN KEY ("courseId") REFERENCES "course"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "course_flow" ADD CONSTRAINT "FK_432b6131c6b3409b965eb0026ad" FOREIGN KEY ("courseId") REFERENCES "course"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "program_benefits" ADD CONSTRAINT "FK_6aeccdff620334324d74d87134a" FOREIGN KEY ("courseId") REFERENCES "course"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "participants" ADD CONSTRAINT "FK_d219b775803c5046a83ca004ebd" FOREIGN KEY ("courseId") REFERENCES "course"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "mentoring" ADD CONSTRAINT "FK_e3937b0a9f65cf4cf87ce1c7119" FOREIGN KEY ("userId") REFERENCES "user"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "mentoring" ADD CONSTRAINT "FK_4e1a7d464b1c40255bf79e9b688" FOREIGN KEY ("courseId") REFERENCES "course"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "registrations" ADD CONSTRAINT "FK_7e5ae7aa55bb98b8b9dcbe32ca3" FOREIGN KEY ("userId") REFERENCES "user"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "registrations" ADD CONSTRAINT "FK_cf9d6bb63110657a72f858f970c" FOREIGN KEY ("courseId") REFERENCES "course"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "course" ADD CONSTRAINT "FK_c6c48d73b3b32e47e9cc1cfc4c4" FOREIGN KEY ("categoryId") REFERENCES "category"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "course" ADD CONSTRAINT "FK_b80ca1ff2ccdcc60c0a7662941c" FOREIGN KEY ("courseTypeId") REFERENCES "course_type"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "portofolios" ADD CONSTRAINT "FK_5bf14a21842b34aaab90b1e65ba" FOREIGN KEY ("userId") REFERENCES "user"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "portofolios" ADD CONSTRAINT "FK_b3f066a48d2f9d4a761d6d10f95" FOREIGN KEY ("courseId") REFERENCES "course"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "mentor_biodata" ADD CONSTRAINT "FK_16642ceba090ecc92d1bb10b43a" FOREIGN KEY ("userId") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "assignments" ADD CONSTRAINT "FK_11bdbd10e3a85d51c380340344c" FOREIGN KEY ("sessionId") REFERENCES "session"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "comments" ADD CONSTRAINT "FK_396fada4663b0ce691461219953" FOREIGN KEY ("assignment_answerId") REFERENCES "answer_task"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "answer_task" ADD CONSTRAINT "FK_7bee33a5b4ed6d30192502e8ab7" FOREIGN KEY ("taskId") REFERENCES "assignments"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "answer_task" ADD CONSTRAINT "FK_108b04110ad10adb3371b1fb7f2" FOREIGN KEY ("userId") REFERENCES "user"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "logbook" ADD CONSTRAINT "FK_a5f70abbe7f92a7e363b1231fba" FOREIGN KEY ("userId") REFERENCES "user"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "logbook" ADD CONSTRAINT "FK_cd3e9e7600669ad4cae357455b3" FOREIGN KEY ("sessionId") REFERENCES "session"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "week_progresses" ADD CONSTRAINT "FK_746edad9baf0764eb2a53fb61f3" FOREIGN KEY ("userId") REFERENCES "user"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "week_progresses" ADD CONSTRAINT "FK_1a0133c164bf75442f7ecc11cca" FOREIGN KEY ("weekId") REFERENCES "weeks"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "session_progresses" ADD CONSTRAINT "FK_c0459263883727f5e02bae606e3" FOREIGN KEY ("userId") REFERENCES "user"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "session_progresses" ADD CONSTRAINT "FK_72f69a4f1e4e8b13d1d2dd406d4" FOREIGN KEY ("sessionId") REFERENCES "session"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "mentor_logbook" ADD CONSTRAINT "FK_8f2e03abc053a791f2a48a8d11b" FOREIGN KEY ("userId") REFERENCES "user"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "mentor_logbook" ADD CONSTRAINT "FK_84a133265454e62374b21725af6" FOREIGN KEY ("sessionId") REFERENCES "session"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_activity" ADD CONSTRAINT "FK_c8d8d7cfc6e3433e725339c952b" FOREIGN KEY ("userId") REFERENCES "user"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "activity_log" ADD CONSTRAINT "FK_d19abacc8a508c0429478ad166b" FOREIGN KEY ("userId") REFERENCES "user"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "attendance" ADD CONSTRAINT "FK_466e85b813d871bfb693f443528" FOREIGN KEY ("userId") REFERENCES "user"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "attendance" ADD CONSTRAINT "FK_4b3ed2a2a22881087475bc2e597" FOREIGN KEY ("sessionId") REFERENCES "session"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "material" ADD CONSTRAINT "FK_384ac50858e585745d1c03fbb3a" FOREIGN KEY ("sessionId") REFERENCES "session"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "session" ADD CONSTRAINT "FK_d16a987478546efd1778f0fc684" FOREIGN KEY ("weeksId") REFERENCES "weeks"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "weeks" ADD CONSTRAINT "FK_b9704041256eec54f93c4a03680" FOREIGN KEY ("courseId") REFERENCES "course"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "partner" ADD CONSTRAINT "FK_4f7df2eaf4bddf85ba7d039df14" FOREIGN KEY ("categoryPartnerId") REFERENCES "category_partner"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "installment_payments" ADD CONSTRAINT "FK_8540362ae6656946814d71adc38" FOREIGN KEY ("paymentId") REFERENCES "payments"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "category_course_types" ADD CONSTRAINT "FK_9cb9d2737820c50a036bd00e6ee" FOREIGN KEY ("categoryId") REFERENCES "category"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "category_course_types" ADD CONSTRAINT "FK_6ce84ef379233fa1a44b31f3c1e" FOREIGN KEY ("courseTypeId") REFERENCES "course_type"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "mentor_technologies" ADD CONSTRAINT "FK_2166e744f1754b3d563e39479ec" FOREIGN KEY ("mentorId") REFERENCES "mentors"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "mentor_technologies" ADD CONSTRAINT "FK_61a698b599cce7aa90d23bd1ec7" FOREIGN KEY ("technologiesId") REFERENCES "technologies"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "voucher_programs" ADD CONSTRAINT "FK_3f413ec454a7f2f52509d492d00" FOREIGN KEY ("voucherId") REFERENCES "voucher"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "voucher_programs" ADD CONSTRAINT "FK_878fddcdb2fd31b3b5a17ac5348" FOREIGN KEY ("courseId") REFERENCES "course"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "course_technologies" ADD CONSTRAINT "FK_7443437646b916f32e640d1b29a" FOREIGN KEY ("courseId") REFERENCES "course"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "course_technologies" ADD CONSTRAINT "FK_0ce505f9c9052d14d4d4cf00b12" FOREIGN KEY ("technologyId") REFERENCES "technologies"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
  }

  public async down(): Promise<void> {
    // Sengaja kosong. Lihat catatan di atas.
  }
}
