export const corporateTrainingPrograms = [
    { no: 1, name: 'Javascript', sub: 'Full Stack Developer Masterclass', category: 'code', categoryLabel: 'Code Class', type: 'Integrated Training', description: 'Pelatihan pengembangan aplikasi web modern dari frontend hingga backend menggunakan Javascript, React.js atau Vue.js, serta Node.js.', cta: 'Minta proposal' },
    { no: 2, name: 'Flutter', sub: 'Mobile Apps Developer Masterclass', category: 'code', categoryLabel: 'Code Class', type: 'Integrated Training', description: 'Kuasai pengembangan aplikasi mobile lintas platform menggunakan Flutter dan Dart dengan antarmuka interaktif.', cta: 'Minta proposal' },
    { no: 3, name: 'Python', sub: 'Web Application & Software Masterclass', category: 'code', categoryLabel: 'Code Class', type: 'Integrated Training', description: 'Pelajari Python untuk web development, data processing, automasi, dan pembuatan aplikasi nyata dengan Flask atau Django.', cta: 'Minta proposal' },
    { no: 4, name: 'AWS', sub: 'Cloud Computing Masterclass', category: 'code', categoryLabel: 'Code Class', type: 'Integrated Training', description: 'Tingkatkan kemampuan mengelola infrastruktur cloud, deployment aplikasi, server, dan arsitektur AWS sesuai standar industri.', cta: 'Minta proposal' },
    { no: 17, name: 'Data Science & AI', sub: 'Thematic Training', category: 'code', categoryLabel: 'Code Class', type: 'Thematic Training', description: 'Bangun pemahaman fundamental data science dan siklus proyek artificial intelligence dengan tools visual yang praktis.', cta: 'Minta proposal' },
    { no: 18, name: 'Generative AI (GenAI)', sub: 'Thematic Training', category: 'code', categoryLabel: 'Code Class', type: 'Thematic Training', description: 'Praktik menggunakan Generative AI untuk menghasilkan teks, gambar, dan kode dengan teknik prompt engineering.', cta: 'Minta proposal' },
    { no: 6, name: 'Figma', sub: 'UI/UX Designer Masterclass', category: 'design', categoryLabel: 'Design Class', type: 'Integrated Training', description: 'Pahami prinsip desain antarmuka, wireframe, prototype, dan design system menggunakan Figma.', cta: 'Minta proposal' },
    { no: 7, name: 'Canva', sub: 'Graphic Designer Masterclass', category: 'design', categoryLabel: 'Design Class', type: 'Integrated Training', description: 'Tingkatkan keterampilan membuat konten visual profesional untuk branding, media sosial, dan presentasi.', cta: 'Minta proposal' },
    { no: 8, name: 'CapCut', sub: 'Video Editor Masterclass', category: 'design', categoryLabel: 'Design Class', type: 'Integrated Training', description: 'Pelajari storytelling visual, transisi, efek kreatif, dan produksi konten video untuk media sosial.', cta: 'Minta proposal' },
    { no: 9, name: 'Canva & Instagram', sub: 'Design & Social Media Planning', category: 'design', categoryLabel: 'Design Class', type: 'Integrated Training', description: 'Buat visual yang konsisten dan rancang kalender konten Instagram untuk meningkatkan engagement brand.', cta: 'Minta proposal' },
    { no: 10, name: 'Canva & TikTok', sub: 'Design & Social Media Planning', category: 'design', categoryLabel: 'Design Class', type: 'Integrated Training', description: 'Buat video pendek yang engaging dengan Canva serta strategi storytelling dan tren TikTok.', cta: 'Minta proposal' },
    { no: 11, name: 'Microsoft Office', sub: 'Masterclass', category: 'business', categoryLabel: 'Business Class', type: 'Integrated Training', description: 'Tingkatkan penguasaan Excel, Word, dan PowerPoint untuk efisiensi kerja dan presentasi data profesional.', cta: 'Minta proposal' },
    { no: 12, name: 'Digital Marketing', sub: 'Masterclass', category: 'business', categoryLabel: 'Business Class', type: 'Integrated Training', description: 'Pelajari SEO, SEM, content marketing, dan analisis performa untuk mengoptimalkan branding serta penjualan.', cta: 'Minta proposal' },
    { no: 13, name: 'Business Management', sub: 'Masterclass', category: 'business', categoryLabel: 'Business Class', type: 'Integrated Training', description: 'Bahas manajemen modern, kepemimpinan, dan pengelolaan sumber daya bisnis untuk profesional dan calon manajer.', cta: 'Minta proposal' },
    { no: 14, name: 'Technopreneurship', sub: 'Masterclass', category: 'business', categoryLabel: 'Business Class', type: 'Integrated Training', description: 'Gabungkan teknologi dan kewirausahaan untuk membangun ide produk, startup digital, dan bisnis inovatif.', cta: 'Minta proposal' },
    { no: 15, name: 'Meta Ads', sub: 'Facebook & Instagram Masterclass', category: 'business', categoryLabel: 'Business Class', type: 'Integrated Training', description: 'Rancang kampanye Meta Ads, atur budget, dan analisis performa untuk meningkatkan engagement serta konversi.', cta: 'Minta proposal' },
    { no: 16, name: 'Public Speaking', sub: 'Personal/Business', category: 'business', categoryLabel: 'Business Class', type: 'Integrated Training', description: 'Latih kemampuan vokal, storytelling, dan presentasi efektif untuk konteks personal maupun profesional.', cta: 'Minta proposal' },
    { no: 5, name: 'Odoo', sub: 'Enterprise Resource Planning (ERP)', category: 'impl', categoryLabel: 'Implementasi ERP', type: 'Product/Service', description: 'Implementasikan sistem ERP berbasis Odoo untuk mengintegrasikan fungsi operasional perusahaan secara efisien.', cta: 'Diskusikan implementasi' },
];

export const corporateTrainingFaqs = [
    { question: 'Apakah ada pelatihan untuk perusahaan atau kampus?', answer: 'Ada. Kami menyediakan pelatihan in-house yang disesuaikan dengan kebutuhan perusahaan atau institusi.' },
    { question: 'Apakah materi bisa disesuaikan dengan kebutuhan tim kami?', answer: 'Bisa. Kami menyesuaikan program dengan tujuan bisnis, kemampuan awal, dan jumlah peserta tim Anda.' },
    { question: 'Apakah beberapa menu bisa digabung dalam satu program?', answer: 'Bisa. Beberapa menu dapat dikombinasikan sesuai kebutuhan tim, atau kami bantu menyusun paket baru.' },
    { question: 'Apakah pelatihan bisa online atau offline?', answer: 'Bisa keduanya. Pelatihan dapat dilakukan secara online atau offline langsung di institusi Anda.' },
    { question: 'Berapa biaya dan durasi pelatihan?', answer: 'Biaya dan durasi menyesuaikan menu, jumlah peserta, dan kebutuhan organisasi. Rinciannya ada di proposal.' },
    { question: 'Apakah Odoo ERP termasuk pelatihan?', answer: 'Odoo ERP adalah layanan implementasi sistem untuk mendukung efisiensi operasional, bukan kelas.' },
];